### ISSUE TITLE
Limit emails sent to students

### ISSUE THREAD

**Issue by fryeguy63** [iomad/iomad#1011]
I really need to be able to stop the "Access to course [course name] granted" emails to students. In my context, I create a single license for each company that allows them to assign students. The license provides access to all courses. We are also using learning paths instead of providing direct access to courses.

So an email that the student is assigned to a learning path is much more valuable than showing access to specific courses.

I see that I can replace a template but I do not see any mechanism to stop the message.

And again, I should absolutely be able to set this up globally, then make specific company changes as necessary.

**Comment by turf212** [comment]
There is a per company setting not for sending of all emails in Iomad 3.6   You can save these as a template set which can be applied to a company when editing or creating a new one.  Company email settings are not tied to a template so you can change them independently of each other afterwards without fear of impacting multiple places.  If you wish to re-apply a changed template to a company, you have to edit and then apply that email template set again which wil replace the current company one.

**Comment by fryeguy63** [comment]
Based on how this works, I can only assume this setting is stored in the DB. So I could conceivably edit the DB records across the board as a means to revising the policy for all companies at once. I believe I have close to 300 companies at this point...

**Comment by turf212** [comment]
It's store as exceptions in the DB.  So, create it for one company and then create an entry in the DB for all of the companies.

Table looks like:

desc mdl_email_template;
+--------------------+---------------+------+-----+---------+----------------+
| Field              | Type          | Null | Key | Default | Extra          |
+--------------------+---------------+------+-----+---------+----------------+
| id                 | bigint(10)    | NO   | PRI | NULL    | auto_increment |
| companyid          | bigint(10)    | NO   | MUL | NULL    |                |
| name               | varchar(50)   | NO   |     |         |                |
| lang               | varchar(20)   | NO   |     | en      |                |
| subject            | varchar(255)  | YES  |     | NULL    |                |
| body               | longtext      | NO   |     | NULL    |                |
| signature          | longtext      | YES  |     | NULL    |                |
| disabled           | tinyint(1)    | NO   |     | 0       |                |
| disabledmanager    | tinyint(1)    | NO   |     | 0       |                |
| disabledsupervisor | tinyint(1)    | NO   |     | 0       |                |
| emailto            | varchar(1333) | YES  |     | NULL    |                |
| emailtoother       | varchar(1333) | YES  |     | NULL    |                |
| emailcc            | varchar(1333) | YES  |     | NULL    |                |
| emailccother       | varchar(1333) | YES  |     | NULL    |                |
| emailfrom          | bigint(20)    | YES  |     | NULL    |                |
| emailfromother     | varchar(100)  | YES  |     | NULL    |                |
| emailreplyto       | bigint(20)    | YES  |     | NULL    |                |
| emailreplytoother  | varchar(100)  | YES  |     | NULL    |                |
| repeatperiod       | bigint(10)    | NO   |     | 0       |                |
| repeatvalue        | bigint(10)    | NO   |     | 0       |                |
| repeatday          | bigint(10)    | NO   |     | 0       |                |
| emailfromothername | longtext      | YES  |     | NULL    |                |
+--------------------+---------------+------+-----+---------+----------------+

foreach company id, template name you can define if its fully disabled (1 in disabled column) or partially.  Change one and you will see what I mean.

**Comment by pamaher** [comment]
If we have absolutely no data in the mdl_email_template table, does that mean there are no email templates? I am having trouble with the same issue -- need to turn off emails, but I can't figure out how. When I edit a company it has no email templates available. I think we may have eliminated them on purpose, but it's been a long time since we did set up, so I'm not sure. Any help you can give would b appreciated.

**Comment by pamaher** [comment]
<img width="394" alt="2019-12-18_13-31-20" src="https://user-images.githubusercontent.com/35539766/71116935-ba26b300-219a-11ea-8868-afd5a7e9cde8.png">

**Comment by turf212** [comment]
If there are no entries in the tables then it means that there have not been any changes from the defaults for the emails.  It's filled with exceptions rather than baselines.  So it takes the text from the language pack and assumes everything is enabled.

In 3.6 on, the template tables changed slightly and there is now the associated language plus whether or not the template is enabled for sending for the user involved and any managers (should they be an ordinary user).  The template editing form also added a bunch of more options (e.g. you can force someone to be CC'd into one type of email always, or you can add a signature, and so on).

You can then save a companies template settings as a template set and apply that template set to another company under the edit company page.  These are not tied together in any way, it simply replaces the company templates with the saved set.   Changing either of these does not change the other.  They remain separate.
