### ISSUE TITLE
Manage IOMAD course settings

### ISSUE THREAD

**Issue by gredionprajena** [iomad/iomad#1181]
Hi,
I've been researching IOMAD 36 for a week. I want to build MOOC like coursera/udemy.

This is what I got (CMIIW):
- Create a new company will create a new category as well
- We can create a course in 2 way:
- [1] via IOMAD->Create Course (/blocks/iomad_company_admin/company_course_create_form.php). We cannot assign category course here.
- [2] via moodle normal way (course/management.php). We can assign category course, course will be unallocated.

I tried to assign some courses to a company and when I open Manage Iomad course settings (/blocks/iomad_company_admin/iomad_courses_form.php)
It produced this error 

![image](https://user-images.githubusercontent.com/31025348/64247501-39b8ab00-cf39-11e9-9bfa-8e53ee6c5aad.png)

Any help is appreciated.
Or does anyone can explain the correct way to input a course.

Thank you.

**Comment by turf212** [comment]
The change of table to be ordered by company shouldn't be possible.  Thanks for reporting this.  I'll get that fixed.

The easiest way to assign a course to a company is to do the following:

in the iomad dashboard select the company you want to create a course under
Go to the courses tab
Click create course

This creates the course under the current company.  You can then change the course settings under the Manage Iomad courses page for it to be shared or licensed or so on.

If you want to bring an unallocated course (because you created it using the Moodle site admin pages) or a course which is closed shared into a company, you can do this under Courses and Assign to company.

FYI - you've likely broken the iomad courses page as it now as a cookie to say you want to sort by company.  You can reset this to get it working agian by using the URL - <YOUR SITE NAME>/blocks/iomad_company_admin/iomad_courses_form.php?treset=1

**Comment by turf212** [comment]
Also, a note on the category.  Any course created within a company will be created under the company category.  This is why it's created in the first place.

**Comment by gredionprajena** [comment]
Hi @turf212 

Thank you so much for your fast response.

Another question:
1. How to assign each course to a category, since if we create a course with IOMAD it will be under the company category?
2. Does IOMAD have a view to show all course belong to a company to the guest user?

I need to have a page like show course by category (i.e. https://www.coursera.org/browse/business)
and by a company (i.e. https://www.coursera.org/stanford)

Thanks in advance.
