### ISSUE TITLE
Can't unallocate single or all licenses within company

### ISSUE THREAD

**Issue by davidpesce** [iomad/iomad#1206]
After assigning licenses to users within a company, they cannot be unallocated. Attempting to do one course, multiple selected courses, or all courses seems to refresh the page, but no action is performed.

IOMAD 3.6.6 (pulled latest today)

**Comment by turf212** [comment]
Licenses cannot be removed if the user has used them and they are not re-usable licenses.  Check the license definitions and if the users have already been enrolled on the course, using the license, then they can't be taken back off of them.  Instant licenses will enrol the users at the time they are assigned.

**Comment by davidpesce** [comment]
What's odd is that I can't even find the license allocation. I was able to remove the majority of issued licenses via the user report, but can't find the last one.

**Comment by turf212** [comment]
Sounds like a data issue.   If you can check on the database what entries are in mdl_companylicense_users for that license id, it will tell you which user ID has it and whether it's in use.  The fact that you could only remove them from the user report tells me that these licenses were definitely in use and the only way to release them was to delete the allocation and enrolment rather than having them in a state where they could be simply taken back.

To give you the thinking on this:
User gets access to the course and has paid for it. (Buys a bottle of beer)
User access the course (Opening the beer)
If the user doesn't want/should be in the course then they have to get another license (Who wants someone's half drunk beer?)
License can't be removed from the user, they have to be deleted throwing any course interaction away allowing it to be assigned another one (Person who sold you the beer takes pity on you and gives you a different, free one).

Instant type licenses remove the possibility of the user having any control of starting the course (You bought a beer at a bar, so they open if before handing it over).  Everything else is the same.

**Comment by davidpesce** [comment]
I ended up rolling back to stock moodle and doing the iomad update on top (again). No issues now because they were wiped. :)
