### ISSUE TITLE
Department Managers

### ISSUE THREAD

**Issue by Blacksheeprules** [iomad/iomad#1250]
I would like to ask a question about department managers.

I know managers receive course completion emails with a course certificate and only from their own company. 

This does not seem to be the case for department managers. 

Is there a way  to have department managers receive course completion email with a course certificate and only from their own department?

Thank-you for any help you can provide.

**Comment by turf212** [comment]
At the moment it's only the company managers who get cc'd into the emails by default.  There is a way using the supervisor email profile field (you need to create this profile field for the company or for the whole site, selected it as that on the edit company page, and then edit the user so that the profile field contains their managers email address.  You can then ensure the template is turned on for the supervisor emails and they will get it.  It's not a neat solution, however, as it was designed for managers who did not have an account on the system.

A neater solution would be to have a switch in the company edit page which allows you to select who gets the emails.  Company manager (default), Department manager or both.  if you would like us to quote for this work, please send an email to info at e-learndesign.co.uk and we can pick this up there.

**Comment by Blacksheeprules** [comment]
Thanks for the info as it was very helpful. I will let you know if we need customizing.
