### ISSUE TITLE
Company Custom Fields

### ISSUE THREAD

**Issue by fffreddie** [iomad/iomad#1252]
Hi everybody
i need to create custom fileds for company profile, something like address, phone, vat, etc. I read previous discussions but they are old enough and there is no solution to the problem. Has anyone got to deal with it?

Thanks in advance

**Comment by turf212** [comment]
Hi there, You can add per company profile fields by clicking on the optional profile fields for the company.  Although, these are for extra user information rather than for the company information.

There was a request for extra company information which came in a couple of days ago to us.  This was specifically for billing information.  I'll link these two if the client comes back and wants it.

**Comment by fffreddie** [comment]
Good!
thanks for your reply and helpful support
