### ISSUE TITLE
IOMAD_38_STABLE or IOMAD_39_LTS ?

### ISSUE THREAD

**Issue by zenny** [iomad/iomad#1273]
Hi,

Excellent work! 

Is there any development on the moodle 3.8.x series which was released in the last quarter of  2019?

Or, won't it be even better to release next iomad, based on next LTS release i.e. Moodle 3.9? Mere wishful thinking. (https://docs.moodle.org/dev/Roadmap)

How does IOMAD compare with Moodle Workspace featurewise and developmentwise?

Thanks and cheers,
/z

**Comment by turf212** [comment]
I'm working on 3.8 at the moment.  Much of the functionality which will go into 3.8 has been back-ported to 3.7 and 3.6 however there are some local changes that will remain on that branch and above.  3.9 will be release in due time too (I'ts meant to be 3 months after release but the 3.7 Iomad release put us a little behind this due to some functionality I was waiting for from a client).

**Comment by turf212** [comment]
On your question about Workplace - Iomad has been around a lot longer and will continue to remain Open Source.  Listing all of the features and putting howto's will be something for this year so you can do a fair comparison.

**Comment by zettrik** [comment]
Hey, are there any news regarding 3.9? I don't see a branch right now and am curious when there will be a release.

I'm asking because I just upgraded a Moodle system to 3.9 and will need another Moodle instance soon. So I would like to go the way with Iomad. Downgrading the existing instance to 3.8 seems impossible. And I didn't find any documenation on how to integrate two seperate Moodles into on Iomad instance.

Thanks for all your work!
