### ISSUE TITLE
Assign groups and manage company groups

### ISSUE THREAD

**Issue by RTewolde** [iomad/iomad#1284]
I want to filter users based on user profile fields information: 
Dashboard -> edit users ->   "Filter results" -> assign the filters  users into course

In moodle you can assign the users into a group (like moodle cohorts) and enrol cohort into course. Is it possible to do this used IOMAD

Many thanks

**Comment by RTewolde** [comment]
What is the benefit of Assign groups and manage company groups.

**Comment by turf212** [comment]
You can still use cohorts within Iomad but you need to be careful about the enrolment as Iomad may not understand that the group the cohort users are being placed into is one which belongs to the company.  When you enrol a user through the Iomad dashboard or through a license it creates a group for the company (if it doesn't exist) in a shared course to hide the users from each other.

The manage company groups and assign groups then allows company managers to create new groups within the shared course and assign company users to them.  These groups are kept apart from other company groups but it then allows users to be further split up rather than all being in the same group (default).
