### ISSUE TITLE
A company's User logged in, but the logo is from another company?

### ISSUE THREAD

**Issue by dyegofern** [iomad/iomad#1287]
I installed a fresh IOMAD instance on my server and created a bunch of companies, courses and users.
Everything looks good on Admin's Dashboard, it switches between companies and etc.

But, when a User (Student) logs on, the Logo on the very top of the page is showing from another company.
Maybe a misconfiguration of mine, but I couldn't figure it out.

Actually, in the courses list (not the menu) it is showing courses from the other company (the same of the logo on top)

Please let me know if someone else found this issue before, I was not able to find it here.

**Comment by turf212** [comment]
If the users is seeing the courses from the wrong company then it's more than likely they are in the other company.  They aren't a company manager and the companies are parent/children are they?

The fact that they are getting the wrong theme and the wrong set of courses suggest they are in the wrong company.

**Comment by turf212** [comment]
Oh, should have said, check the mdl_company_users table for the impacted userid.  Normal users should only have one entry (at this point in time).

**Comment by amirtq** [comment]
there is also another experience that I have with this issue on seeing resources from another company.
I had this issue when I was logout from company and with same browser login to another company
It seems there is some cookie issue so what I do is using different browsers for different companies else, clear browsing data after logout from a company then login to another one so there will not be any cookie conflict.
Its not bad if you even check what I said maybe you are suffering from same issue.

**Comment by turf212** [comment]
The SESSION variable gets cleared when you log out.  It may be cache though?  I have a lot of issues with Chrome "remembering" what a webpage looks like even though it's completely changed.  E.g. when I've set up a server URL incorrectly then correctly.

**Comment by amirtq** [comment]
Its an overall chalenge with IOMAD since Moodle by itself is very cookie and cache oriented in other hand, IOMAD day to day working tasks are related to multi tenancy, the final way I have found to work without issue was to login in different browsers for example Firefox for site admin, Chrome for Company manager and Opera for student.
Also as I found, different host names for tenants will not bring any issue means its possible to login to multi tenants at a same time in one browser, with different host names and without any session conflict issue

**Comment by turf212** [comment]
Question - Do you see this after login only?  I.e. does the company parsing which is already in place protect the site at the start?

There is a Moodle function set_user_cookie() in session lib which set us the cookie the user is using after login.  If we add company details to that cookie name for users in a company then they should get their own cookie/cache information for each company they have logged in from rather than the site default cookie name.  Let me test.

**Comment by turf212** [comment]
Ah, no.  That's not the issues at all.  We are branding the logout page to the last company which you were logged in as.   So the issue is if the computer is shared.  When you log out as an admin and then log in again using the same browser it will log you in with the last company selected pre-selected and providing you the branding for that.  If you put a URL which is a working company hostname, it will overwrite the selected company and branding, giving you the correct one for that company.

So the issue is as follows:
- We want branded login / logout pages which can be passed company parameter details on the URL.
- We want branded login / logout pages which can be passed via site URL
- The logout page has already removed the SESSION variables before it's displayed  so to allow for it to be branded we need to pass it back something even though the user is not logged in.

It's the last one which is tripping us up / is tricky.

Give that it's on a shared browser this will happen (so Admin will see it more than anyone or people testing users across different companies) is this much of an issue, or is it more of an annoyance?

**Comment by turf212** [comment]
Further testing -
The the logout page captures the current selected company details and then redirects you to the login page, which sets up the $SESSION variable and puts the company details and theme into it.  Using the browser to go to the site after that keeps the last selected company.

**Comment by amirtq** [comment]
I also found another challenge it may be a serious security problem!
In the first browser tab, login with a user account in Company A
open another tab in same browser and login as company manager to Company B then you will have access level of company manager to all courses and licenses and ... of Company A with company manager of Company B

**Comment by Annesha-maker** [comment]
I also found another challenge is that  In same browser, when trying to login with different account credentials
When I am logging in with different account credentials, showing error as ”Error reading from database”.
Steps to Reproduce:-
1)	Login as main Admin, navigate to other pages then logout.
2)	Login as Student or any other account, not able to see dashboard page .

**Workaround** 
Logged in with different browser or guest.

**Comment by adrianb83** [comment]
I have the same problem, when you logout from an user from company A and login to another user from company B, all datas from A are visible to B. Its a caching problem. 
Everything works ok in incognito mode.
Thanks,

**Comment by turf212** [comment]
I've updated the login code so that it will force change the user's company to their own company if it doesn't match the one which is held over from log out.  As previously mentioned this would only be an issue if users from different companies were sharing the same browser immediately after each other.  Or admins.  Doing testing. :)
