### ISSUE TITLE
User Enrrolment email not sent (iomad)

### ISSUE THREAD

**Issue by dsquare58** [iomad/iomad#1296]
![Screenshot (211)](https://user-images.githubusercontent.com/44236940/77863322-5c821800-7219-11ea-9d02-2ef403897722.png)

**Comment by dsquare58** [comment]
@iomad

**Comment by michalludynia** [comment]
Check if your scheduled task "email report"  is running correctly. Go to site admin -> server -> scheduled tasks

**Comment by dsquare58** [comment]
![Screenshot (229)](https://user-images.githubusercontent.com/44236940/77974323-ae48a200-72ee-11ea-8d7d-9f5de77e1476.png)
 Now this is the back trace I got when I run cron.php

**Comment by turf212** [comment]
So there will be an email in your queue which is being sent to the admin account on the site (user id = 2).  That user account is no longer tied to a company so it's not bringing back any departments. (which is why the departmentid IN () is an empty list).  If you remove those email from the mdl_email table it will allow the queue to process properly.

_delete from mdl_email where userid = 2_
