### ISSUE TITLE
Adding "optional profiles" to report adds it for all companies

### ISSUE THREAD

**Issue by davidpesce** [iomad/iomad#1327]
When adding an "optional profiles" field to a company and then to the iomad settings (for reports), it adds that field for all companies.

Does it make more sense to simply use Moodle's custom profile fields or to limit the columns display on other companies?

The shortname already requires the company name in the setting (profile_field_companynameshortname).

Thoughts?

**Comment by turf212** [comment]
when this was developed the client which wanted to use it wanted it for "global" optional profile fields (== ones which had been set up within the Moodle menu pages rather than the ones which were added added through the Iomad dashboard).  I suppose it would be sensible to check which ones were in the currently selected company, although that may mean the list is huge,  So, the second of those options. :)

**Comment by turf212** [comment]
I've added checks to the course report, users report, user license allocations report, user login report , and email report to check that the profile field is allocated to that company or not allocated to any before showing it.

**Comment by davidpesce** [comment]
It works like a charm! Thank you!!

**Comment by Werrie09** [comment]
Hi Gents,

I hope you can be of assistance. I was able to add any General, Additional names, Interests, Optional fields but when I create a custom user field in the tenant and try to add that field to the reports the system doesn't allow me. I am not sure what I am doing incorrectly.
