### ISSUE TITLE
SignUP option not coming on login page

### ISSUE THREAD

**Issue by subodhkant** [iomad/iomad#1336]
I have downloaded and installed ... but SignUP option not coming on login page.

Can anyone help me why it not comming on login page and how to get it ?

**Comment by turf212** [comment]
If you haven't already set up the system to enable self signup it won't show.  You need to go to site administration -> plugins -> authentication -> manage authentication and enable email authentication.  You also need to enable self sign up by then selecting the email authentication method for it.

For Iomad, you need to then go to site administration - plugins - local plugins - local iomad signup.

**Comment by nadjavon** [comment]
> If you haven't already set up the system to enable self signup it won't show. You need to go to site administration -> plugins -> authentication -> manage authentication and enable email authentication. You also need to enable self sign up by then selecting the email authentication method for it.
> 
> For Iomad, you need to then go to site administration - plugins - local plugins - local iomad signup.

For a newly installed Iomad 3.8, above done but Iomad Signup does not come up, comes up only when set as an alternative url in the Manage Aunthentication page which logs you out.  Please walk us through  a step by step process to have the Iomad sign -up page instead of the Usual Login Page, so Users can Login directly to their Iomad Company /school. Thanks

**Comment by turf212** [comment]
This was moved over to the core Moodle /login/signup.php page which now supports all of the same parameters and settings as the older local/iomad_signup/signup.php page.
