### ISSUE TITLE
Company manager can manage course activity creation like External tool,quiz .

### ISSUE THREAD

**Issue by Annesha-maker** [iomad/iomad#1345]
A company manager can manage course activity creation like External tool, quiz and also can it delete the activity.
If yes , can tell me what role I need to apply because now I am facing an issue in creating an external tool and quiz.
"Course or activity not accessible".

**Comment by turf212** [comment]
Company managers***** who have created courses get the client course editor role otherwise, on courses which are not licensed they get the client course access role.  These are broadly editing teacher and non editing teach roles.  You can change the permissions of these to add in the new capabilities but you need to be careful if you are dealing with shared courses.

***** This is assuming you have not separated the company manager roles to allow them to be enrolled as a student where these course roles are given to company users who are assigned as an educator.
