### ISSUE TITLE
Courses not visible under categories

### ISSUE THREAD

**Issue by w33vils** [iomad/iomad#1367]
Hi,

Apologies if this has been asked before. I wouldn't find it.

I have an issue where course categories are visible (by all roles), but the courses within are not visible to anyone else except the site admin. The courses are set to visible. Users can however search individual courses and find them (and enroll) but if a user open a category to view courses within, it is blank.

I upgraded from a previous moodle installment to iomad version 3.8.

Thank you!

**Comment by turf212** [comment]
Iomad uses the course categories for repositories for company courses.  So each company will have their own course category assigned to them and users are only allowed to see categories which are for their own company or are not assigned to any company.  If courses are shared then they can see the course but it's likely the company course category you are falling foul of.  This is to revent users from seeing courses which may mention other companies in the name, for example.

So, if you want all of your courses to be visible to all of your companies, you will need to put them into categories which are not associated with any companies.  If this is what you have done, please let me know so I can test this.

**Comment by w33vils** [comment]
Thanks!,

I think my issue is stemming from the fact that I am moving from an existing core moodle setup (With over 3K courses distributed inside multiple course categories) to realize the benefits of iomad. 
 But I realize the only way for users to 'see' the courses is if i assign all of them to the company, under the same company category.

My goal was to have the same categories and courses from the previous core moodle setup available to everyone.

As it is now, Users can use the search function to get to a course, but cannot see the course listing under any categories.

Any extra tips to help my cause? Or I am limited to assigning all the courses to one big company category instead of multiple.

thanks:)

**Comment by ghost** [comment]
I have this question too in 3.10. A user who is a Moodle system level Manager but not in any Iomad courses should have a way to see what they normally see.

I note that Iomad seems to add a Prevent to the Manager role categories created in Iomad for the capability moodle/category:viewcourselist  which is allowed by default. However, unsetting or allowing this did not fix this issue. 

I am hoping there is a simple way to fix this issue with a permission change, otherwise it would mean the only admins can get around such limits to manage courses across multiple categories, and that is not a safe thing to do.
