### ISSUE TITLE
Upload Users using csv : theme assign error

### ISSUE THREAD

**Issue by nileshnpathade** [iomad/iomad#1371]
I am trying to upload csv for creating users. and I want to assign theme for each users. 

"theme" is not a valid field name. 

I am using  IOMAD 3.6.8

**Comment by turf212** [comment]
The user's theme is automatically set in the code when they are assigned to the company (which happens as part of the Iomad dashboard upload users) where they are given the company theme.  In other words, you don't need to worry about the theme being set as it happens automagically.

**Comment by nileshnpathade** [comment]
But my user are in different different companies, and they use different themes. So, I want to assign theme user wise. ?

Can you help me how to do this. ?

**Comment by amirtq** [comment]
if you are uploading users for different companies, you should use separated files, each time upload users of one company and choose that specific company from dashboard company selector.
as I know, it is not supported to upload users for multiple companies in one shot.

**Comment by turf212** [comment]
Exactly correct.  At the moment you need to select the company you are uploading users for and then upload the users for that company via CSV.  This is so that we keep away as much as possible from the Moodle core code to help speed up new version testing.  (the less Moole core code changes we have the easier the testing is).
