### ISSUE TITLE
Change IOMAD logo and name on dashboard

### ISSUE THREAD

**Issue by ken4ward** [iomad/iomad#1376]
I'll like to replace the IOMAD logo and name with the companies'. I'll remove the alert text of "Your company is ....". I've searched the pix directory and couldn't find the iomad_logo.png. please, where else can I make this changes?

Secondly, is it possible to have a custom URL per company, either using a subdomain or URL. Something like this should do.
Custom subdomain: https://abc.iomad.com
Custom URL: https://iomad.com/abc

Thanks hoping to hear from experts.

**Comment by turf212** [comment]
It's possible to use the first of the custom subdomains. If you look at https://demo.iomad.org you will see how it's set up.  You need to point each subdomain to your website on the webserver and have appropriate SSL certs.

If you are using an Iomad theme or a theme which has been customised to understand about companies, then you can change the company settings to add in their logo instead of the Iomad/site one.
