### ISSUE TITLE
Dynamic contents for for custom menus

### ISSUE THREAD

**Issue by ken4ward** [iomad/iomad#1379]
I've created pages for the custom menus at the top of each company in IOMAD. These pages are independent as they inherit nothing from the IOMAD-Moodle system. 

I'll like to know the files to query so that the pages also inherit the custom menus and the CSS properties of the IOMAD Boost theme. 

Also, since each page is an attribute of a company, is there a way to create a simple backend where the companies can add their content instead the admin hardcoding it on all pages? 

Please, help. It's urgent

**Comment by turf212** [comment]
If you are using the standard Moodle PAGE variables for displaying the page information then it will ensure that the user viewing the page will see the appropriate theme with all of the CSS and logos added.

To add in something which allows for company managers to create their own page content wouldn't be simple.  It would need to have the forms to create the content and then filter so that the company would only see their own.  I would have started with the Moodle site pages functionality (using mod_page) and made it company aware.
