### ISSUE TITLE
Duplicate entry for key 'mdl_scorscoetrac_usescosco_uix'

### ISSUE THREAD

**Issue by pong106** [iomad/iomad#1393]
I was trying to restore several mbz course under a company. The mbzs comes from another Moodle system. 

Steps done:
1. Create a company
2. Site administration -> Restore course -> Import a backup file -> Next -> Restore as a new course -> (select the company name) -> Next -> (Change Course name and short name) -> Next -> Perform
3. Hits a Duplicate entry error (screenshot below)

![Screenshot 2020-06-30 at 3 42 14 PM](https://user-images.githubusercontent.com/12490740/86098148-4b7ec680-bae8-11ea-9470-9eeebd8d3933.png)

Details:
Commit: IOMAD_38_STABLE (a229f67653dfbc97191979c341d46ad56a98ec16)

**Comment by turf212** [comment]
This is a data issue with the mdl_scorm_scoes_track table where you have a duplicate entry which is breaking the index.  It's not an Iomad bug (SCORM is a core Moodle module and we haven't made any changes to it).  I suspect the issue is within the source site you are pulling the data from.  Fromt he error, it's trying to add an entry for the user id 0 (there should be no such user ID within Moodle/Iomad) to the mdl_scom_scoes_track table.  If you run the following on the source site:

_Select * from mdl_scorm_scoes_track where userid=0;_

and it passes back any lines, I would consider deleting them from the table and then performing the backup again.
