### ISSUE TITLE
Learning Path is not working properly

### ISSUE THREAD

**Issue by santoshndev** [iomad/iomad#1401]
I am trying to create learning paths but course list and student list does not get populated, also delete, enable/disable button is not working.

**Comment by turf212** [comment]
Which version of Iomad are you using?  (check the /local/iomad/version.php of the installation and there will be a release version for the plugin.

**Comment by santoshndev** [comment]
im using IOMAD Moodle 3.8.3+

**Comment by turf212** [comment]
Just checked this with latest $release  = '3.8.3+ (Build: 20200612)  As pushed last to the git repository.  (The last changes to learning paths were a while ago so that shouldn't be an issue). 

Go to dashboard
Select a company from the dropdown.
Go to courses tab
Click on Learning Paths
Click to add a new path
Give it a name and description
Save it
Click to add courses to path
List of courses appears on the right (Does your company you have chosen have chosen have courses allocated to it?)
Create a path with several courses and groups
Go back to the learning path lists and click to assign students
Students appear on the right hand side (Does your company have users)
Add some users to the learning path
Go back to the learning path list
Click the delete button
Learning path is removed.

If this is not working for you, what errors, if any, do you get when you turn on full developer debug and go through those actions?

**Comment by santoshndev** [comment]
issue resolved thanks...
