### ISSUE TITLE
How to remove default assignment of courses to course educators 

### ISSUE THREAD

**Issue by likhith-ch** [iomad/iomad#1416]
If we assign a person as course educator by default they are assigned to all the couses in a company. 
And if we remove all course educators assigned to a course and assign only concerned course educator they are getting assingned as Client course access roles. How to overcome that.
Thank you

**Comment by turf212** [comment]
If the switch to enable educators instead of company managers then they will be assigned the client course access role to all non-licensed courses.  This happens automatically and they are put into appropriate groups if the course is shared.  If educators are not enabled this action happens for company managers instead.

If you want to enable only some company educators to some company courses then you can use licenses to achieve this.  There is a special educator license type which can only be assigned to educator users.  This removes the default 1 to many.

The thinking behind this is that a company who has purchased access to manual enrolment courses has no restriction on the number of users who are on that course so all educators/company managers get access.
