### ISSUE TITLE
User bulk upload broken after update?

### ISSUE THREAD

**Issue by enrarelloem** [iomad/iomad#1426]
When uploading users of a company with the bulk process in the past, they were in a course in the group of the company when license and course were selected during the upload process.

In Iomad installations updated after 1 July, they are enrolled in the course but not members of the group of the company in the course.
I checked the process with an Iomad of Moodle 3.8.3 build 20200511. This build sorts the users to the respective company groups in the course during bulk upload. Neither an Iomad updated 1 July nor two installations updated today to 3.8.4 Build 20200713 behaved this way.

I reckon this is a bug in the bulk upload process.

**Comment by turf212** [comment]
Somewhere in a merge the group assign parts got lost.  Thanks for reporting.  I've added them back in.  Please update.

**Comment by enrarelloem** [comment]
Thanks Derick!

After updating, there is only one strange thing left:
- I uploaded dummy users to my test system(s) and assigned a license and course.
- The system(s) reports: users uploaded, licenses assigned.
- The list of participants in the course shows the users in the correct group, but they are marked as "not current" and cannot login to the course.

Funny enough, if I create an empty course and copy all content from the original course by "import", I can upload users to this course and they are marked "active" in the list of participants. I have to create a license for this course first of course.

Before today's update, this behaviour was the same. The only difference now is the correct group assignment. The effect is consistent through two productive and two test systems.

**Comment by turf212** [comment]
If the users are license users and you have switched off the license enrolment method on that course then they will be marked as enrolled but their enrolment will not be current.  Check the course enrolments under the course administration menus and, if required switch it back to licensed within the Iomad course management page.

**Comment by enrarelloem** [comment]
Thanks, for coming back to this Derick.
The courses are licensed with closed sharing.

**Comment by turf212** [comment]
Does the course enrolments match this within the course itself?  (Iomad just keeps track of this in the mdl_iomad_courses table but doesn't do any checking if someone has manually changed it in the course enrolments within the course).

**Comment by enrarelloem** [comment]
The bulk upload puts them into the correct course. The license is assigned in the process. (Now again) They are in the correct company group in the list of participants in the course - however, they are marked as "not current". This is the case immediately after upload.
The strange thing is that everything is ok with a newly generated course with the same content (imported from within the new course by "import" ). I just checked: When I export the course to a file and use this file for the import (on the same or a different system), the error is back in the new course.

Could this be a second problem connected to something broken in the course (database table) itself rather than being part of the upload problem?

**Comment by turf212** [comment]
I think I know what's happening here.  If you are using course1,course2,course3 etc in the CSV file then this will manually enrol the users onto the course (although will also put them into the correct course groups).  As the course is licensed, they will get the marked as not current as the manual enrolment process is switched off.

To assign a license to a set of users via CSV upload, you can select the license and course from the license selector on the form.  This uses a different route to enrol users as it's possible, depending on the license, for the users not to be enrolled immediately that they are given the license.  (They get to choose when they unwrap it)  If you want to mimic the same proces as manual enrolment, you can make the license instant access which enrols the user onto the course when the license is assigned.

I think, from what you have said, you have mixed up the manual enrolment and license enrolment course paths which is why you get users on the course but not current.

**Comment by enrarelloem** [comment]
Hello Derick,
Course and license are assigned in the upload process, as described above by you, not by the CSV file. The CSV just contains username, firstname, lastname, email and lang.
