### ISSUE TITLE
Add users from moodle to iomad

### ISSUE THREAD

**Issue by ken4ward** [iomad/iomad#1430]
I'd created some users in Moodle earlier and want to add them to a company in IOMAD, I can't seem to find any functionality to do this. Am I missing anything? Please help!!!

**Comment by enrarelloem** [comment]
How did you get the users from Moodle to Iomad? By import of a course?
- Chose the company in the dashboard.
- Chose the "Assign users" in the Companies tab. To the right, you should see your Moodle users - if you imported them with a course.
Hope that helped. Otherwise some more info on the way you got the users from Moodle to Iomad might be helpful.
