### ISSUE TITLE
How to use Webserver hostname in iomad company using NGINX

### ISSUE THREAD

**Issue by zuhebahamed** [iomad/iomad#1438]
Hi

I have installed iomad and created 2 companies. i want to give separate White Labelled login Urls for 2 companies.

help me how to create separate URLs using Webserver hostname in iomad company.

Thanks

**Comment by halaalajlan** [comment]
Hi there,

First you have to point the company domain to your moodle address, then edit your companies settings and set the hostnames.

**Comment by asamolion** [comment]
@halaalajlan I've tried that but the company URL redirects to the main URL. It does not persist throughout the session like the demo site.

**Comment by turf212** [comment]
This was only added to Iomad 3.6/7 from around March of this year.  It was part of the 3.8 release.  If this isn't working as per the demo site then patch to the latest versions of the code you have or upgrade to one of the ones which does support this.   Prior to this, the system would simply redirect to a login page with the company automatically selected rather than allowing the URL to persist.

**Comment by asamolion** [comment]
I got this to work. 

Basically the issue was in the NGINX configuration. You have to create a separate NGINX configuration for each company and set the server_name as the webserver hostname of the company.

**Comment by turf212** [comment]
I've updated the title to reflect this so someone will be able to find it later in a search :)

**Comment by moossaab** [comment]
Thanks for post
I could do it easily
But the problem: there is no restriction in custom URL
all users can use all custom domains to access their school site
