### ISSUE TITLE
Company categories display to guest

### ISSUE THREAD

**Issue by devam319** [iomad/iomad#1446]
Hi there,
Is it possible to show the category and sub categories of specific company to guest users ?
kindly let me know

**Comment by turf212** [comment]
The only way to show course categories to users is to have those users within a company.  The guest user is a special user in Moodle so can't be added to a company as this would mean anyone who hadn't logged in (i.e. guest user) would belong to that company and would have their company changed when they did log in.

If you are trying to show the course catalogue, then you can put courses into course categories which do not belong to any company and the courses would then be seen by every user (because they wouldn't be filtered out).  This could be as many or as few courses as you want but they will be visible to everyone on the site.
