### ISSUE TITLE
Iomad emails not sending -Fatal error: Uncaught Error: Class 'core\task\scheduled_task' not found

### ISSUE THREAD

**Issue by tbeachy** [iomad/iomad#1456]
IOMAD_38_STABLE
I'm particularly interested in the external supervisor email, but in working on this, have realized that pretty much all Iomad-related emails are not sending.  I have seen couple emails get created in the outgoing report, but they do not send or get received.

- Cron is running every minute with no errors on any jobs.

- All emails are enabled to supervisors and managers in email templates

- I am using Trema as a theme (if that makes any difference)

- Normal Moodle emails **are** being sent and received

- I do not have any dept managers assigned because we don't have dept managers -- it is a self-service system.  But do want the user to be able to input their external supervisor's email in the profile field set up for this purpose.

- When I edit an email template, I have no way of designating the supervisor email field (I get no suggestions for either To: or From: fields).  I do have errors in local/email/error_log that confirm this problem -- PHP Notice:  Undefined property: stdClass::$emailto... etc.

- Users and courses are properly assigned to the company.  Completions are showing up correctly in dashboard

Thanks for any help!

**Comment by tbeachy** [comment]
Tried testing this on iomad demo site, but cron is apparently not running there.

**Comment by tbeachy** [comment]
Started logging my cron output...
Finding this error:
```
Fatal error: Uncaught Error: Class 'core\task\scheduled_task' not found in /home/oe9us12ub0cm/public_html/local/iomad/classes/task/cron_task.php on line 5

Error: Class 'core\task\scheduled_task' not found in /home/oe9us12ub0cm/public_html/local/iomad/classes/task/cron_task.php on line 5

Call Stack:
    0.0006     401480   1. {main}() /home/oe9us12ub0cm/public_html/local/iomad/classes/task/cron_task.php:0
```


I'm not sure why it wasn't showing when running the cron job manually with debugging turned on?  There are no time/date stamps, so maybe this is from a previous iteration.

**Comment by tbeachy** [comment]
Some updates:

- completion_course_user emails are now being written to the db and show up in the outgoing email report, but they are never received at the other end (waited over an hour, and checked spam folder).  As a side note, they also don't have any info in the to: or from: fields
- completion_course_supervisor emails are not even being written to the db

**Comment by tbeachy** [comment]
I have verified that iomad cron error is still writing to the log every 1 minute when cron runs.

**Comment by tbeachy** [comment]
In the mdl_company table, I have an 'emailprofileid' and a 'supervisorprofileid'.  If I update the  "External supervisor email field" in edit company, it affects the 'emailprofileid' field.  But so far I cannot find anything in the interface that affects the 'supervisorprofileid' field. 
What is supposed to be there?  I also haven't found anywhere in the code yet that references this field...

**Comment by turf212** [comment]
As per emails: The Iomad cron task does not need to be run separately from the standard Moodle cron task as all Iomad tasks are set up as scheduled tasks and are run through the Moodle cron.  Running /local/iomad/classes/task/cron.php from the command line will throw that error as it is the scheduled task file and the command line environment will not have any of the required Moodle paths set up.  It's always best to run an individual task for testing from Site administration -> server -> scheduled tasks.

The mdl_company table entries which you have identified are:
emailprofileid - The id of the user info field which is used to store the email address of a supervisor
supervisorprofileid - Is not being used (and it likely a duplicate caused by a merge back in 3.2)

To send emails to an external supervisor:

Create an optional profile field which will be used to store one of more email addresses (separated by a comma)
Edit the company and set the external supervisor email field to the newly created one
Edit the company users to put a valid email address into that field
Ensure that the required email template is on for both the user and the supervisor
Cause the email to be generated.

The external email address is added as a CC but is programmatically sent as a separate email as simply adding the CC headers doesn't do anything.
