### ISSUE TITLE
Course access - Question

### ISSUE THREAD

**Issue by nileshnpathade** [iomad/iomad#1464]
![qu](https://user-images.githubusercontent.com/13468332/93593261-6703ba00-f9d1-11ea-981a-e44bfcbdc833.jpg)

Sorryfor bad images...

Please help me to understand course accessing for company manager role and others.

Accessing means, 

He should not shared course with other sub company
He should not enroll course with other sub company

Or Other sub company or sub child company user can not access and even should not see on any page of system.

According images, : 

First question is : 
Can person can become Company manager of cc1, cc4, and cc6. Which are under another parent company's like com1, com2 and com3.???

2nd Question is:
How can restrict to company manager of com1, for close and open shared course to another company like com2 and com3 and there's child??

Please help me to understand.

**Comment by turf212** [comment]
Any company manager of a company which has child companies is automatically a company manager of those child companies.  The list is presented to them in the same way as the site admin gets it but it only contains the appropriate company.

As a company manager, they get access to all of the courses which are not licensed that are assigned to a company with the company client access (non editing teacher equivalent) role.   This is so that they can have access to the course reports for the company allocated courses.  If the courses are licensed then this is not allowed (as it would use up a license) but switching the option of to enrol company managers as non-users in local iomad_settings allows a company to have educators (not necessarily company managers) and educator licenses (where they get the client course access role).

There isn't any way of preventing a company manager from a parent company to have less access than a company manager of a child company as their role is logically the same.

**Comment by nileshnpathade** [comment]
Thanks for replying....

But I need to assign company manager for only selected company. it may be multiple company??

And 

About 2nd Question is:
How can restrict to company manager of com1, for close and open shared course to another company like com2 and com3 and there's child?? 

Com1 has closed shared course that only can see and access by cc1, cc2 and cc3.

In IOMAD these closed shared course can see any company and make it available for other company like com2 and com3. 

If IOMAD is multi-tenancy project it should not see by other company which don't have any relations.

com1 and com2 doesn't having any relation... ??

Please help me to understand.

**Comment by turf212** [comment]
If you go to the assign department users/managers menu item and select company manager as the type of user you want to assign , there is an option to show company managers from external companies.  You can then assign a company manager from one company to another company without there being a parent child relationship between the companies.

**Comment by nileshnpathade** [comment]
But if I assign a user as company manager to com1. 

Then 

same user want to assign to com2 as company manager then it will remove com1 company manager.

It means one user will be company manager of ONE company only. I can not assign one user as company manager to multiple company.

And any close shared course able to see by any company, Why ? If I don't want to make this availed to other company and only want to share with my child company.

**Comment by turf212** [comment]
Users can be in multiple companies with different roles as of IOMAD 4.3
