### ISSUE TITLE
Report of grades for users with not valid license. 

### ISSUE THREAD

**Issue by michalludynia** [iomad/iomad#1468]
Hi!
I need to remove user access to course after specific period of time. It can be done by license settings easily - user get unenrolled from a course by "valid for" or "course cut off date" settings. But I want company managers have access to user grades after it. For now, I can see only course completion report with total grade of user.
Is there any way to analyse/report users specific grades (from activities, quizes itp) not only the total one after user unenrolement?

**Comment by turf212** [comment]
When the user is removed from the course using the options under Manage Iomad Course settings, it is with the intention that they are completely removed so that they can retake it at a later date.  If you just set the license up so that the user has access for x days then only their enrolment is removed, leaving their previous course interaction.

Is this not what you are seeing?

**Comment by michalludynia** [comment]
That's true, but it's not my case at all. 

I need an ability to revoke access to course from student and still see his gradebook. In standard moodle instance I would suspend users instead of unenrolling them. 
@turf212 Is this possible with licenses?

**Comment by turf212** [comment]
You can still suspend the user's enrolment within the course when they are using a license to access (which is what I assume you mean rather than suspending the users access to the whole site).  They will still be removed from the course when the conditions for timing from the license enrolment ending are met (in the same way as having an enrolment end date works for any enrolment).

So, you can set the end date conditions for the license to be a very long time in the future and use suspend.

FYI course grade is kept within the Iomad reports when a user's enrolment ends.  Just not the individual grades of course activities.
