### ISSUE TITLE
How to create categories from company manager

### ISSUE THREAD

**Issue by ahamedzuheb** [iomad/iomad#1477]
Hello

I want to create some categories in iomad company and assign courses to it so that categories and courses visible to only this company. other companies should not see categories and courses of this company.

help me to achieve this requirement.

Regards
Zuheb

**Comment by bavdalimbaev** [comment]
@ahamedzuheb i know what in iomad/moodle hasn't this function.

**Comment by turf212** [comment]
Iomad doesn't have the functionality for doing this within the dashboard.  You would need to create a new role to give to the company manager in question which has access to add/edit categories and assign it within the companies category.  Any courses created using the Moodle admin tools will not belong to a company (which is why the tools are on the Iomad dashboard) so there are likely to be some pitfalls for this.
