### ISSUE TITLE
Auto assign license to the self registered users

### ISSUE THREAD

**Issue by michalludynia** [iomad/iomad#1500]
Hi!
Is it possible to assign a license automatically while user has created an account?
My users use oAuth2 to create an account and they are assigned to companies by domain. I need an ability to enrol them to shared, licensed course automatically. I know, that's possible with non licensed courses, but I'm using licenses and I need them. 
Is that somehow possible? Are there any alternatives?

**Comment by turf212** [comment]
At the moment there is no option to do that for self sign up but you can choose to assign a license and a course when you create a user either from the new user page in the dashboard or from the bulk user upload from the dashboard.  This doesn't help in your case.

We are approaching the rules system within Workplace, which would be useful across the whole site (on this event do these tasks).  How would you see this working?  What happens if the license has expired? Been used up?  How would you see this being managed from an admin point of view?

Some answers to my own questions - 
If the license is no longer available for any reason, do nothing.
1 - User doesn't get course, complains to manager, manager then sorts and fixes issue.  Pros - Simple Cons - could allow for more automation.
2 - We check if another license within the company is available for that course and assign from that instead.  Otherwise do the same as for 1. Pros - Less involvement with managers/admins having to do work.  Cons - More complex so more areas to fail.

We already mimic 2 when the option is set within the Iomad settings to re-assign a license when clearing down a user from a course.  When ticked on automatic or manual clear down of a user from a course the system checks to see if they can provide from the same license, assigns if so, if not checks to see if there is another available license and uses that instead.  If there is nothing which is appropriate it does nothing.

The admin could be as simple as just adding any course to the auto-enrol.  If they are manual then it does it.  If they are a license it checks to see if that is possible and does that.  A better solution may be incorporate this into something else I've been considering for a while, which is making the Iomad Course Settings be configurable per company.  We can then have an option that they are auto-enrol or not as a switch (as well as all of the benefits of per company course life-cycle).  That page needs some re-work to make it more AJAXy anyway

**Comment by michalludynia** [comment]
Hi! Thanks, for detailed answer. That possibility would be awesome to make the whole process more automated. 
It could be just a checkbox in the license management form if the license should be auto assigned to new created users. There is already possibility to assign license during manual creation and file import, so it could be named like "Auto assign to self registered user". If the license has expired or used up it should just not assign it and as you said user would complain to the manager. 

We just want to make whole process less engaging for managers, because they complain us about permanent license management. 
The easy model like that would be perfect:
1. Company buy an access to platform with one license for 1000 users. 
2. New users are auto assigned to company by domain and can immediately start a course, because license is assigned.

**Comment by michalludynia** [comment]
Hello @turf212, 

Could you share some information are there any plans to introduce this feature? 

I came back here today, because the same need happened again ;)

Regards!

**Comment by turf212** [comment]
added under commit b114a27963973b718b63d5c75196f2fc9fccd5da
