### ISSUE TITLE
How can a company manager give users the role of creating courses within the company?

### ISSUE THREAD

**Issue by totoromaum** [iomad/iomad#1527]
Hi, I would like to manage many schools within my organization by allowing each school manager to give permission of creating course within their organization to corresponding school users. In this way, each company manager feel less burden of creating entire courses for their company. Please let me know if this is possible.

**Comment by turf212** [comment]
Hi, this is not currently possible without some creative work with roles.  If you set up the department manager (which I suspect you are not using) so that they can create courses, split the managers away from being teacher types (site admin -> plugins -> local plugins -> local iomad settings -- and untick _Enrol managers as non students_) then the department manager can also be assigned as an educator which means that they can create courses and will be given the client course editor role with them.

You would want to play around with the roles to make sure they do everything you want.  As long as you keep the enrolment permissions so that they have to use the Iomad dashboard then they wont get access outside of their box.

**Comment by totoromaum** [comment]
Thank you for the reply, @turf212!
