### ISSUE TITLE
Can Suspended company be activated again?

### ISSUE THREAD

**Issue by ratishsaini** [iomad/iomad#1528]
Hi is there a way to activate a suspended company? If not, is it possible to create a new company with same company details to make it active again?

**Comment by turf212** [comment]
You can re-activate a company by going to the manage companies Iomad menu item, clicking on the "show suspended companies" option and clicking on filter.  All of the suspended companies (denoted by having an (s) at the end of their name) will have an option to unsuspend them.  This puts the company back to where it was when it was suspended.  FYI - If this was done automatically due to the contract end date within the company definition, you will need to select the suspended company first, edit it to change this value to be in the future and then unsuspend the company otherwise it will just be automatically suspended again.
