### ISSUE TITLE
Trying to install iomad but facing issues, wanted to know whether  we need to install moodle seperately and iomad seperately or only iomad alone?

### ISSUE THREAD

**Issue by adityamishra97** [iomad/iomad#1548]

**Comment by turf212** [comment]
The Iomad code contains the full Moodle code as we need to make some core code changes to allow for the multi-tenancy to work.  What are the issues you are experiencing?  What version are you trying to install?

As a rule of thumb, Iomad (because it is basically Moodle with some extra packages) follows the same minimu requirements for PHP and so on as for the same version of Moodle.  The install docs on the Iomad website are out of date (and also not ever green) so install one of the latest versions matching one of the supported versions of Moodle using the Moodle requirements.  The installation steps are exactly the same right up to creating a company.
