### ISSUE TITLE
Emailing certificates of completion to learners who didn't take a course

### ISSUE THREAD

**Issue by pamaher** [iomad/iomad#1554]
Using IOMAD Dashboard to assign courses to students. After we do that, the students are sent certificates of completion even though they haven't even started the course yet.

**Comment by turf212** [comment]
The certificates are sent when the students reach the requirements for course completion.  It sounds like there is something wrong with the course completion criteria which means that they are immediately being marked as complete after being enrolled on the course.

**Comment by pamaher** [comment]
We're still having this problem after combing through requirements for course completion. Can't see a connection. It seems like there is something wrong with the IOMAD enroll user option.

**Comment by pamaher** [comment]
I'm really at wit's end and would appreciate any insight. I have not changed completion option at all. We upgraded recently and I wonder if that could have caused this issue. Anytime anyone is assigned to a course through the IOMAD dashboard they are automatically shown as complete. But in the DB (mdl_local_iomad_tracking) there is not a completion timestamp. It's null. I don't understand what is happeneing.

**Comment by turf212** [comment]
Apologies for the radio silence on this.  We were badly affected by the OVH fire and had to bring most of our server estate back from DR.  It's been a little time consuming - as you can imagine.

I did find a very esoteric bug with the completion tracking and email sending where, depending on the order of the event listeners, one would cause the other not to fire.  I put a patch under commit 01d0396d00d6270489626fcdcb30ee3a508e31ce to the branches Tuesday of last week.  The scenario was:

User completed the course - course completion event is fired
Local iomad track consumes the event and marks the user as complete in the local_iomad_track table, creating the certificate
local/iomad/ consumes the event, checks to see if the record is already there and then skipped it.

This doesn't sound like what you are experiencing, however, and this is more how the courses are set to complete within Moodle (as the users are immediately completing the course).

What are the course completion criteria settings you have for the course?  (Go into the course - Course administration -> course completion settings)
For the criteria, if any are based on completion of activities, what are the completion settings for those activities.

This sounds like the underlying issue.  A user is enrolled on the course and immediately meets the course completion criteria - firing the completion event and causing all of the consumers to fire as well.

**Comment by pamaher** [comment]
Thanks for the response and I'm sorry to hear about the fire! 

Our completion criteria used to be two items:

- Complete SCORM with passing grade or a status of complete (depending on the course)
- Complete survey

The certificate was then available to the user.

Recently we removed the surveys so our ONLY current course completion criteria is to pass or complete the SCORM. Do you think that could be causing the problem -- the removal of the feedback activity?

Thanks so much for any help you can give.

**Comment by pamaher** [comment]
A little more info. When we assign the course to a user using the IOMAD dashboard, we noticed the local_iomad_track table has a start date, enrolled date, but no completion date -- which seems correct to me. But then the certificate is automatically available to them even though they haven't touched the SCORM yet. It's no longer being emailed (we turned that off for now), but they can access it.

**Comment by turf212** [comment]
What restrictions do you have in place on the certificate activity?  It sounds like there is no restriction there so the user will gain access to it on enrolment.

You can check what the user has met on the course completion criteria using the course completion report within the course itself.

FYI - All of this, within the course, is core Moodle.  This sounds very much like a course configuration issue.

**Comment by pamaher** [comment]
For graded SCORMs the restriction on the certificate activity is that they must achieve a certain score on the SCORM. For non-graded SCORMs, the restriction on the certificate activity is that they must complete the SCORM. I know it sounds like a course configuration issue, but it doesn't seem to be. We've not had this issue in the past and have been using IOMAD for several years.

**Comment by turf212** [comment]
what version are you using?

what is the internal course activity report say for a user who has just been enrolled?

**Comment by pamaher** [comment]
Moodle release 3.8. Maybe you can help if I explain our problem better. We need to allow users to repeat a course each year and get a new certificate for compliance training.  We used to archive and recreate courses for this purpose but that was a pain and unwieldy. This year, we used a recompletion plugin from Dan Marsden-- we wanted it to archive data and allow reissue of IOMAD certificates with new dates in the same course when people are re-enrolled.  We don't think it worked right because users keep getting automatic completions when we assign a class. It finds the SCORM from last year and assumes it's done.  I contacted Dan and he said our requirements are better suited to be part of the IOMAD code. Is this something you could help us with? Thanks so much.

**Comment by turf212** [comment]
Your problem, as Dan rightly says, is that the plugin you have installed does not clear down user interactions from a course.  So when you re-enrol the user to the course, they are immediately marked as complete again as they still meet all of the course completion criteria.

To fix:
Remove this plugin - it's not required.
Edit the course settings in the Iomad course settings page for this course so that it has a value in the "Training expires after" column.  This enables automatic clear down of users from the course after this time scale once they have completed it.
If you want the user to be cleared down before this, then add in a value to the "days to email before training expires" column when, as long as the template is enabled, a user will be sent an email to say their training in the course is no longer valid. OR add a value to the "enrolment expires after" column which will kick the user out of the course after this period once they have completed the course.

The underlying process here will remove the user from the course and clear down all core interactions which they had with the course.  In your case SCORM CMI interactions and attempts along with any Iomad certificates which have been saved _in the course_.  Any saved Iomad certificates and reporting information within the Iomad reports will be kept.

You now have a system which removes user enrolments and course content based on when they complete the course.

If you want to clear down the user's course interactions before then, say they hit the maximum number of attempts and have now "failed" the course, then you can use the clear button in the user's course completion report to wipe their current enrolment and interactions allowing them to start again.

**Comment by pamaher** [comment]
Thank you! We reset courses on Jan. 1 each year. Is it possible to set these numbers to that rather than their relative completion date?

**Comment by pamaher** [comment]
Derrick - one more question related to the instructions you posted above. When I make changes on the IOMAD course settings page (actually the dashboard) so it has a value in the "Training expires after" column, I don't see that reflected in the table where i would expect to see it: the mdl_iomad_courses table – that field is still set to “0”, which is the default. Am I looking in the right place? Thanks!

**Comment by turf212** [comment]
You need to update and save the form foreach change (I'm working on making that form more AJAXy) which may be why it's not in the table.

Regarding your other question - if you are simply clearing down the course once a year, and so don't care about any users who may have been enrolled the previous day, you can use the inbuilt Moodle course reset item in the course administration menus.  You can also automate this with Moosh.  The Iomad cleardown is to allow for a rolling cleardown on a per user bases rather than clear everything once a year.  The thinking behind the rolling one is someone may be enrolled on the course the day before (or of) when you clear the course and lose all their work.  It depends how you are running your courses though.  Either is valid just you now have options :)
