### ISSUE TITLE
how to allocate the privilege of creating licenses to company managers

### ISSUE THREAD

**Issue by ababacardiop** [iomad/iomad#1559]
I want to give the company manager the privilege to create course licenses to manage the courses of his own establishment.

**Comment by turf212** [comment]
Is this so that they can act as a reseller for your courses?

If so:
Create a new system role called reseller which has the capabilities of :
**Split a license to a child company
Edit my company licenses**
and potentially
**Add a child company**
Assign this role to the company manager who will be the reseller using the Moodle assign system roles menu.
Create an overall license for the parent company with all of the courses and licenses which they have agreed from you.

They will then be able to take the license which you have defined and split it up to any/all of the child companies however they see fit and within the amounts of the license you've already given them.

If it's not for that, then why are you using licenses and not manual enrolment?  Is there a specific use case?

**Comment by ababacardiop** [comment]
Yes I want to use the manual registration but the teachers will not be able to edit the courses in this case.
thanks for the help

**Comment by ababacardiop** [comment]
I want to give the company manager the privilege to create courses, teacher editors and students. Apparently, I have to create a license for each course so that teachers can edit them.

**Comment by turf212** [comment]
If the course has been created by the company manager, then they would be given access to edit the course.  I'm going to be changing the control of this so that you, as an admin, can decide which courses a company manager should have editing access on (rather than the arbitrary fact that they created it).

**Comment by SerigneBabaca** [comment]
Hello can you help me to give teachers the privilege of editing the courses. You said you are going to help me, how are you going to help me?

**Comment by SerigneBabaca** [comment]
it's always ababacardiop

**Comment by turf212** [comment]
option to grant access to a course added in 30afcba9d21a9e25c8c58bf78eea3e9eeaca25e4 which allows admins to give editing access to courses that are not licensed or shared in any way.  Company managers/educators then gain access to change the content.

Note - this will never be given to license courses as these are courses that they have purchased access to from you and not courses that they shoudl hen be able to edit.
