### ISSUE TITLE
Can't find data record in database table course_categories on my IOMAD 3.9

### ISSUE THREAD

**Issue by daneth** [iomad/iomad#1581]
Dear All,

I have notice that cannot create Course from IOMad dashboard while always get error message Can't find data record in database table course_categories. 

Could anyway can help to advice how to fix this issue? 

Best Regards,
Danet

**Comment by turf212** [comment]
You will have deleted a course category which should belong to a company without clearing the rest of the underlying data.  When you create a company a company category is created for that company as a place to store any courses created within that company.  If you remove that, then you get the error.

You need to fix this by firstly checking which company course categories are missing (they are created with the company name so you just need to compare the list of each of them), creating any which are missing, and then updating the company record in the database so that the category field is the id number of the field in mdl_course_categories with the same name as the company/you've just created.
