### ISSUE TITLE
H5P interactive video not being reset with unenrolment

### ISSUE THREAD

**Issue by gregosullivan** [iomad/iomad#1583]
When a user re-takes a course (one that they have previously completed and have since been unenrolled from) the H5P interaction is not being reset - i.e. the answers from their previous enrolment are still showing, and the video starts from where they left off (usually the very end).

**Comment by turf212** [comment]
Where is the H5P interactions being saved?  Can you provide a test so I can check we are clearing everything out?

*edit - sorry I meant "Where in the database is the interactions being saved?"

**Comment by gregosullivan** [comment]
Thanks!

It appears they are being stored in mdl_hvp_content_user_data

What kind of test should I provide you with?

**Comment by KaramTreohan** [comment]
Hi Derrick, 

I'm new to BVS CareTutor, my name is Karam. We have been having a few issues related to this query posted here a while ago. We are finding that hvp data is kept when clearing or unenrolling a course. In fact, we think it is only when the course is edited manually through moodle that status on the data for these courses is updated to "RESET" on mdl_hvp_content_user_data. And so the problem remains that users start the video from the end when they do their refresher training. 

The developer tried creating a manual clear code, adding this to the end of your base clear process. This is the code she used: 

// Remove HVP info. Note this is H5Ps added via the plugin not core. 
if ($hvps = $DB->get_records('hvp', array('course' => $courseid))) { 
    foreach ($hvps as $hvp) { 
         $DB->delete_records('hvp_content_user_data', array('hvp_id' => $hvp->id, 'user_id' => $userid)); 
         $DB->delete_records('hvp_xapi_results', array('content_id' => $hvp->id, 'user_id' => $userid)); 
    } 
} 

We ran a test on 400 enrolments we wanted cleared and this process took 13 hours to run on the test site. 

There are many more enrolments to clear data from. We were hoping to add this section to the clear code for all future clears as well. But it seems that it is not feasible and our website just cannot handle clearing each hvp record individually. 

Is there a way we can format this code differently or any suggestions you can make so that the system pushes this code and any future clears much faster?

**Comment by turf212** [comment]
Core H5P added in bc799da1c834 Optional plugins should handle their own data deletion on un-enrolment.
