### ISSUE TITLE
reporter only view

### ISSUE THREAD

**Issue by hetcxp** [iomad/iomad#1593]
hi there,

i have the following issue with the company reporter only role. if i assign this role to a user in a given department, then i see that the user have access to both the department and to the whole company reports as you can see on the image below.

![image](https://user-images.githubusercontent.com/19639688/117169382-70deff80-ad9f-11eb-9811-2f78c8daf8af.png)

and if i give the role in a subdepartment, then things get worse.

![image](https://user-images.githubusercontent.com/19639688/117170574-84d73100-ada0-11eb-8255-bcaa13c4c153.png)

is there a way to limit the user to see only the reports of the department / subdepartment he is assigned to as company report only?

regards.

**Comment by hetcxp** [comment]
hi @turf212 have you being able to have a look at this?

**Comment by turf212** [comment]
The functionality when you assign a user to a department has changed slightly due to users allowed to be in multiple departments.  What you have done here is assign the user to a new department as a report only role.  The user is now in the company top level department and **also** the new department with that role.  You need to remove them from the top level department as well.

I've never liked the functionality of this page but it was as good as we could think of at the time.  In 4.0 there is now functionality in the Edit users page to add/remove departments and roles to users which is a lot more intuitive.
