### ISSUE TITLE
Auto-allocation of Corporate Managers to Self enrollment courses

### ISSUE THREAD

**Issue by LMS-iomad** [iomad/iomad#1616]
For any self-enrollment course, all the corporate managers are getting auto-enrolled. Can we change this behaviour so that only desired participants enrol themselves?

**Comment by LMS-iomad** [comment]
Hi - Can anyone check this issue?

**Comment by turf212** [comment]
Yes - this is the correct behaviour.  Managers are given the client course access role or client course editor role (non editing teacher and teacher role types) so that they can run in-course reports on their users.  If you want to decouple this you can untick the option for _Enrol managers as non students_ under site administration -> plugins -> local plugins -> local IOMAD settings at which point you can designate users as Educator roles instead who get this functionality.
