### ISSUE TITLE
Iomad - user not enrolled on a course but has licenses sees all available courses on front page

### ISSUE THREAD

**Issue by turf212** [iomad/iomad#162]
User has valid license for courses but has not enrolled on any yet.  User doesn't see any of the licensed courses and instead sees the list of all courses.

**Comment by turf212** [comment]
not repeatable.

**Comment by pm-tatiana** [comment]
@turf212 
I am having a related issue.
Usually when I have a course that's closed shared, not licensed. I assign the course to the company I want and the company manager (CM):
1. can see the course in the list of available courses or my courses
2.CM gets enrolled as Company manager and Client course access and linked to a specific group with same name as the company http://prntscr.com/eta2c0 - This is wonderful because it allows segregation of data and allows me to modify permissions on the company manager and client course access roles so that company manager can check the grades only for those users that belong to his own company (same group). 

**When the course is closed shared and licensed**, however, doesn't work as I need it to work.
When I assign the licensed course to the company, my company manager is not able to see the course listed in the courses available to the company because all of the enrollments methods are disabled. 
This causes my CM not being enrolled into the course as usual. Instead, I need to go a create a license for the company and allocate the course to the license. If I want the course to be visible to the CM, I have to allocate him a license. That's fine. I can live with that BUT, those brings me another issue. 
My CM gets enrolled into the course "Student" and as "Company Manager".
I don't want my CM to be a student. I want him to have the roles he usually gets AND I want my CM to be allocated to the group he should be in.

Also, Company users under this licensed - closed shared/open shared course scheme. Are not segregated by company because they are not added in a group as usually they would if they were enrolled into the course via "user enrollment".

Do you have any suggestion regarding this?

**Comment by pm-tatiana** [comment]
no one? :/
