### ISSUE TITLE
Migrate Moodle 3.9 site to IOMAD 3.9

### ISSUE THREAD

**Issue by rmeske** [iomad/iomad#1654]
I have an existing Moodle 3.9 site and am looking to migrate to IOMAD 3.9.

In reading other posts it sounds like all that needs to be done is replace the Moodle code with IOMAD code and it will launch.  However, I am getting an error upon launch: Table "company" does not exist

 What is the correct process to get IOMAD to update the database?

**Comment by santoshedfibre** [comment]
i think you need to first install block/iomad_company_admin and local/iomad plugin first then you can migrate

**Comment by turf212** [comment]
Migration from Moodle to IOMAD process is as follows

- BACK UP YOUR WHOLE SITE!
- Replace all of the Moodle code with the corresponding IOMAD code (same version or higher) keeping any optional plugin you have already installed.
- Run the upgrade process (CLI = php admin/cli/upgrade.php or Site administration -> Notifications from the browser)
- You will now have the IOMAD code on your Moodle site and you can start using this.

You will need to do stuff to migrate your users to companies which you have created.  How you identify which users should go to which company could be down to email domains or profile fields (institution/department are a good start for example).

You need to ensure all of your courses have _Course_ completion criteria set (as this is what the reports run on) and then you can import the data to the IOMAD reporting tables.

**NOTE - If you simply install the plugins then some of the multi-tenancy parts where users/courses and so on are kept apart will not work.  There are changes to core code to allow for this (Moodle doesn't understand about companies) which is why it's all packaged up as a full release and not a suite of plugins.
