### ISSUE TITLE
Moodle 3.11 or Moodle 4

### ISSUE THREAD

**Issue by syusanjun** [iomad/iomad#1688]
Do you have a release plan for a version compatible with Moodle 3.11 or Moodle 4?

**Comment by jlb224** [comment]
Also interested

**Comment by rmeske** [comment]
Interested in Moodle 4 integration for 2 main features, better responsiveness and the Report Builder.  Given that 4.0 has some major changes, is it safe to assume it will be a year before we see IOMAD integrated with Moodle 4.0?

**Comment by turf212** [comment]
IOMAD 4.0 has been pushed to the repo's today.  We are typically 3 months behind Moodle release but for a nuber of (valid) reasons did not create IOMAD 3.11.  That turned out to be the wrong decision in some ways as the release for 4.0 took longer than expected.  Still.  We've released before Workplace ;)
