### ISSUE TITLE
Front page tree menu with courses, categories and subcategories (IOMAD moodle 38 stable)

### ISSUE THREAD

**Issue by jbrodo** [iomad/iomad#1705]
Hi all,

we are unable to show the correct tree menu of courses, categories and subcategories associated to the company to all the users (e.g. student users).

We noticed that some sub categories are not shown to student but only to admin user, as shown following:

![image](https://user-images.githubusercontent.com/2954998/182570914-363ca2e7-7835-4b55-a9e4-a1ec54e1f6be.png)

Do you know how to show subcategory to students and logged users?

We tried to:
- create a new course for the company from the iomad dashboard
- assign coursers to the company
- assign user to the company
- create a departement , assign the course and the users to the departement
- static analysis of php files

Every attemps did not make changes or improvements.

**Comment by SimoBigno1992** [comment]
I have the same issue too

**Comment by turf212** [comment]
The way that course categories for a company was changed/fixed in February of this year (commit 248f9cc80917bfb53a45366364a244c3a3525b61 on 3.9 branch).  This allowed subcategories under company categories to be seen by company users as, logically, they were company categories.

This wasn't pushed to 3.8 as it had dropped out of support by then.

Hope this helps!
