### ISSUE TITLE
Emails to managers

### ISSUE THREAD

**Issue by matiz22** [iomad/iomad#1712]
I have question about these email templates.

License expiry date warning
Manager course completion warning report
Manager course completion warning report - digest
License useage warning

First three, I tried setting it weekly on specified day, dailly and it was never sent to managers. The question is what triggers to send these mails? And problem with useage warning is that I set one license for one guy and mail also wasn't delivered. It has to be exactly 90%? Is there any docs to explain how it works or  is it  bug/issue?

The rest of email templates(promoted to manager, course not started etc) is delivered without any problems.

**Comment by turf212** [comment]
The license expiry date warning is sent out when a license assigned to a company is due to expire
Manager course completion warning is sent out when a user has not completed a course within the expected timeframe set in the IOMAD course settings page
The digest email for this is sent out with the same triggers but if the email digest is set within the company settings as well
License usage warning is sent out when the number of used licenses is nearly the same as the total number of licenses available within the license.

We are working on docs for everything (as it's been sorely missing)

**Comment by matiz22** [comment]
is Manager course completion warning report and 
Manager course completion 
warning report - digest based on this?
![image](https://user-images.githubusercontent.com/95767720/189116077-fa2542fa-d68e-4ef7-b82f-fc5e597ca588.png)

**Comment by turf212** [comment]
This is a Moodle setting and not anything which IMAD has any knowledge of.  The course expiry and not completed emails are sent from values which you put into the Manage IOMAD course settings under the Courses tab in the IOMAD dashboard.

There you can set how long training is valid for and how soon before the training is valid a warning email is sent out.  (amongst many other settings).
