### ISSUE TITLE
Course completion mail sent without conditions fulfilled

### ISSUE THREAD

**Issue by enrarelloem** [iomad/iomad#1734]
After update to Iomad 4.0.4 (Build: 20220912) from 3.9.17

Conditions for course completion:
- Condition: Activity completion: Quiz "Exam"

Conditions in Quiz Exam:
- Student must receive a grade to complete this activity
- Student must receive a passing grade to complete this activity (75.00)

Testuser logs on to the course, does the test and fails. Still an e-mail is sent that the course was completed successfully.
This behaviour was not shown in Iomad 3.9.x before the update.

Furthermore, I noticed that the Completion Report by Course always shows the result of the first attempt - even if a certificate is issued with a second attempt (Grading method: Highest grade).

Any ideas or help would be appreciated. Thanks!

**Comment by enrarelloem** [comment]
PS And the mail is even sent out, when the course completion mail is deactivated in the templates (by applying a template set to all companies).
Could this be related to this https://github.com/iomad/iomad/issues/1731

**Comment by encodecreate** [comment]
I'm seeing the same issue -- course completion emails being sent out even when the course completion template is deactivated. The text of the email is also not following the correct template.

Text of email sent: 
"Congratulations!

You have completed the course [course name]"


Text of template:
"Dear {User_FirstName},

Congratulations on completing the training course {Course_FullName}. Please find attached a copy of their certificate for your records.

The certificate is also available from your dashboard should you need a copy in the future."

**Comment by encodecreate** [comment]
Adding to my previous comment:

These course completion emails are also not showing up in the outgoing email report.

**Comment by dallenk** [comment]
i believe I am also seeing this one as well.

**Comment by turf212** [comment]
If the emails are not in the mdl_email table/showing up in the reports then these are not IOMAD email templates.  The workflow for sending emails in IOMAD is to:

Call the local/email API to create an email template
This stores the email with the various headers etc into the mdl_email table
local/email cron runs and processes the emails which are due to be sent out and haven't yet.

If you search for the body of the email in your language pack (you will need to select all of the php files) does this show up in any other plugin?

**Comment by turf212** [comment]
Regarding what is stored in the IOMAD reports - when the course completed event is fired (the first time a user meets all of the course completion criteria) the current course grade and completion dates are saved to the mdl_local_iomad_track table.  This event only fires once (unless you clear down the completion information but we sanity check to make sure it's not recorded twice using the enrolment timestamp).  If the student continues to undertake work with the course, e.g. retakes an quiz  and gets a higher grade, this is not recorded as the event doesn't fire again.

To get around this, set up your course so that it completes when the student wants to or when is actually important.  I.e. if they need to get a high enough grade to pass the course and get the certificate then make the course completion criteria meet that.  If you are allowing re-takes then you can add in a separate switch/trigger that causes course completion to fire.

An example of this could be

Course has a quiz which allows re-attempts
Course has a certificate which is award on course completion
Grade is the highest grade for the quiz

Add in a Feedback activity which becomes available when the minimum passing grade is achieved
Make the certificate and course completion dependant on completing the feedback
Make access to the quiz dependant on not completing the feedback
Scaffold the Feedback to tell the student that completing it will complete the course for them and they won't have any further access to the quiz.

Student can do the quiz as many times as they want.  When happy, they submit the feedback, which completes the course and generates the certificate.  Student can't go back and reattempt the quiz.

**Comment by encodecreate** [comment]
Thanks @turf212 , checked the language pack and that led us to a solution.

For anyone else getting course completion emails that don't match Iomad settings, there's a new email notification feature from Moodle Core that got added in this upgrade. So the core Moodle code can send out emails for events like course completion even when the parallel Iomad emails are turned off.

If you want to disable these Moodle Core course completion emails, head to Site Administration > Messaging > Notification Settings.

**Comment by enrarelloem** [comment]
EDIT: Thanks @encodecreate! I was not aware of this new Moodle feature. However, switching off the messages in the website administration of Moodle **didn't silence the unwanted mails**.
Website administration:
![grafik](https://user-images.githubusercontent.com/39500812/200518371-c3b0927a-be95-4969-9472-1473bcf0b741.png)
Iomad dashboard template set (for all companies)
![grafik](https://user-images.githubusercontent.com/39500812/200518871-2be9c17e-72e9-4e1e-a30f-c5ce0b5e1ac7.png)

@turf212 you suggested
"Course has a quiz which allows re-attempts
Course has a certificate which is award on course completion
Grade is the highest grade for the quiz"

Your scenario is very close to our actual scenario which produced the unwanted mails. I added the feedback (which was part of the course anyway) to the conditions for course completion. Now everything seems to work fine including the correct mark in the completion report in the dashboard.

**Comment by enrarelloem** [comment]
Thanks @turf212 and @encodecreate
