### ISSUE TITLE
Upgrade from IOMAD 3.10.x - 4.0.5 - Admin stuck at edit profile screen 

### ISSUE THREAD

**Issue by davidpesce** [iomad/iomad#1745]
I upgraded an instance from 3.10.latest to 4.0.5 and when logging in as the admin, I get stuck at the edit profile field. Seems like there are required fields not set, but all required fields are set.

**Comment by davidpesce** [comment]
Turns out I had a company (deleted) that still had custom profile fields that were required. Rolled things back to 3.10.x, removed the required (deleted) company profile fields, and then successfully completed the update. It seems that profile fields are not deleted when a company is deleted.

**Comment by turf212** [comment]
There isn't any mechanism to delete a company from the dashboard which is why there isn't anything to remove the profile fields either.  If you've deleted the company by another method then, yes, you would need to make sure that you also removed the company profile category (and all the profile fields) all of the company departments, company_user records, licenses, license_course entries, local_iomad_track table entries, course category, and likely a number more that I can't think of off the top of my head.

IOMAD follows the Moodle method of just marking things deleted (in our case suspended) so the integrity of the data can be kept.
