### ISSUE TITLE
Can Authentication be setup per company?

### ISSUE THREAD

**Issue by rmeske** [iomad/iomad#1749]
Hello,

I thought I saw somewhere that authentication can be set at the company level, but I am not finding it again.

If Company A wants to use Microsoft for authentication, Company B wants to use Google, and so on, is there a way to configure that?

It looks like that would require modifying the admin settings for authentication plugins on a per company basis and I am not seeing a way to easily override those settings in Moodle.  Is this something that is on the future feature list?

Ron

**Comment by dallenk** [comment]
I use LDAP for one company, and local login for 14 others right now.   Simply use the authentication plugin and set it as the last option. 

![image](https://user-images.githubusercontent.com/2725066/209410920-978bb0a8-cdc4-4613-a696-2265416edc29.png)


I don't believe there is a "per company" setting since a company is simply a catagory in Moodles view.

**Comment by rmeske** [comment]
@sgvfr ,

Thank you for your reply.  That is what I thought.  So with multi-tenancy if two or more different companies what to setup SSO, there is currently no way to do that.  

I imagine that I could duplicate the authentication plugins to create multiple versions and tie this in with the company allowed domains in some fashion.  Or create a new authentication plug-in that extends the current one and introduce a way to setup based on a company domain.

**Comment by turf212** [comment]
IOMAD OIDC and IOMAD SAML2 both allow for per company authentication.
