### ISSUE TITLE
Restrict a basic role in a specific company

### ISSUE THREAD

**Issue by matiz22** [iomad/iomad#1754]
I have question about restricting a basic role in company. Is this possible to restrict access to a plugin block or url. I have one company which don't want to see a ranking from plugin,? I made special role but i can't assign it to a company. Any ideas how to make it. I'm using level up xp moodle plugin, maybe someone had a similar problem.

**Comment by turf212** [comment]
The company restrictions will only work with IOMAD plugins (as we've added a second layer for iomad::has_capability() etc) so if the plugin doesn't understand about companies then it won't work with the extra company restrictions.  You may be able to use conditional access rather than roles but that depends on the plugin.
