### ISSUE TITLE
Webservice function core_course_get_courses_by_field broken by recent IOMAD change

### ISSUE THREAD

**Issue by abias** [iomad/iomad#1807]
After updating to IOMAD 3.9.20, we had to see that calls to the `core_course_get_courses_by_field` webservice function are answered with an `unknowncategory` exception instead of a course object.

We call this webservice function with these parameters:

```
wsfunction: core_course_get_courses_by_field
field: idnumber
value: 23722-016
```

Digging into the code, I had to see that there was a recent addition in https://github.com/iomad/iomad/commit/d93e3ef1df8a6556afee4cd19f13914508f776ce which seems not to be related to any Github issue and which triggers this side effect.
After removing these lines, the webservice function is working again.

I would like to ask you to fix this issue so that the core_course_get_courses_by_field function is working without problems again.

**Comment by turf212** [comment]
This was added in so that there was a check in place so that logged in users could not view course categories which they shouldn't be able to see.  It passes all of the categories to a function in /local/iomad/lib/iomad.php - iomad_filter_categories which has a capability check for block/iomad_company_admin:company_view_all which, if passed, does nothing with them and returns them as is.

`    public static function iomad_filter_categories( $categories ) {
        global $DB, $USER;

        // Check if its the client admin.
        if (self::has_capability('block/iomad_company_admin:company_view_all', context_system::instance()) && empty($userid)) {
            return $categories;
        }
`

If you add that capability the user you are running the webservice as then it will work as it used it.

**Comment by abias** [comment]
Thank you @turf212 for your reply and explanation.

We will test soon if the additional capability will solve this issue. But, reading through your explanation, I expect it to work.

It's just a pitty that this change was introduced within a stable branch without a Github issue explaining the change. Thus, it was totally unexpected for us to see the webservice break after a minor update.

I will close the issue for now.

Cheers,
Alex
