### ISSUE TITLE
Allowing a user to belong to multiple companies

### ISSUE THREAD

**Issue by spadkins** [iomad/iomad#1821]
I want to be able to set up IOMAD so that a user can belong to multiple companies.

In this article "Companies Overview" (https://www.iomad.org/documentation/documentation/administration/companies-overview/)
it says that "If you have the capability, you can switch between different company “realms” from within the IOMAD dashboard".

Can ordinary users ("students") see this dashboard?
Can they be a member of multiple companies so that they can switch between them?

**Comment by groiso** [comment]
Did you manage to solve this problem, I also need to do the same thing.

**Comment by spadkins** [comment]
So far, I have determined that

1. IOMAD coopts some fields in the mdl_user table to store the company that the user belongs to (the "home company"). There can only be one. However, this home company does not limit what courses the user can see or take. (I think.) (I am still investigating what the significance is of the "home company".
2. IOMAD introduces a family of new tables around "mdl_company", to implement its multi-tenant capability. One of these tables ("mdl_company_users") implements a many-to-many relationship between companies and users. I am still investigating what this does. (see the attached or embedded diagram)
![iomad-db-users-to-many-companies](https://github.com/iomad/iomad/assets/1544418/83fdaa91-5fb7-4839-ba84-946986750266)
3. There is a capability that can be added to an Authenticated User role that allows users to see other companies. I am exploring how this works and what it takes for a user to see multiple organizations in their list.

So I am still optimistic that with a bit of configuration (not coding), I can make IOMAD work the way I want it, where users have some visibility into the courses of multiple companies.
I will keep working on it until it works or I give up, and I will let you know here.

Stephen

**Comment by dallenk** [comment]
If it helps, I have 23 companies, some sharing courses open and/or closed.   other company users can see those courses but not users of other companies.

Does that help?

**Comment by turf212** [comment]
You are kind of correct, but none of the profile fields tie to the company allocation.  There is a job which syncs that data (institution.department) back to the profile but it's optional and not what is used.  There is instead the mdl_company_users table which is the table that holds the user => company relationship.

Technically it's possible for a user to belong to more than one company.  This already happens with company managers in parent companies and child companies.  The problem is more the management of what then subsequently happens.  E.g. Company manager role is assigned as site level (we don't have a company context - though in typing that this may be something which would help) so if a user is a company manager in one they are a company manager in all.  What if the tenant doesn't want that user to be a company/department manager?

If a course is shared between two tenants and a user is already in the middle of it, does the user need to do it twice if they are granted access again in the second tenant? If they have already completed it and it's within their current course expiry date? From a tenant point of view yes, from a user point of view, no.  Also, if yes then the course record with the valid dates and then warning emails would be impacted as the user still has an in date course.

What theme does the user get when the log in? If you aren't using something else to pre-define the company then how does the user choose.  This also impacts on what courses the user can/can't see when they aren't enrolled and it could impact unused, allocated licenses.  If tenant A has their own set of custom menus, then the user would need to switch to them in some way to see them if they were in the realm of tenant B.

What email templates does the user get for the automatic emails (you've not completed a course, your training is expiring, etc)

What happens if a user is deleted or suspended in one tenant only?

As I say, there is a large amount of implications here that need some hard thinking.  We've had a few requests about this functionality recently and it's definitely something I'd like to be able to achieve. There is a reason why we haven't done it yet though :)

All thoughts and workflows very welcomed!

**Comment by spadkins** [comment]
So from what you said, roles are granted to users systemwide.
And if I wanted a user to be a Company Manager in one company (tenant), a Teacher in another company, and a Student in another company, then we would HAVE TO modify the code so that a COMPANY context could be created.
Is that right?
How hard would that be?

**Comment by turf212** [comment]
Again - not quite.

The default setting is for company/department managers to be given teacher type access to manual/self enrol courses (they are locked into company groups on shared courses to stop them seeing users from other tenants.  These are the client course access roles (based off non editing teacher).  If the company manager is given rights to create courses then they get the client course editor role.

If the option to Enrol managers as non students is unticked in local iomad settings plugin (default is ticked) then this set up another user type, educator.  Educators, instead of managers, get the teacher type roles.  If you are using license course access then you can create an educator license specifically for users with this designation which will enrol them as a teacher type instead.

The issue is that the IOMAD dashboard exists at the system level.  So the role is granted at a system level with rights to the various parts of the dashboard that you have allowed.  There is another level of capability check within IOMAD which wraps around the standard Moodle has/require capability checks that check for the capability for the users role within the company. This allows you to turn something off for Tenant A but keep it on for Tenant B.  It's for everyone who has that role in the company so what is missing is for a specific user which a specific company do they have that capability.  A check could be done against the record for the user specifically within that company, which would work, however this is not the issue.

What do you do when the data from one tenant clashes with the data from another from a standard user perspective and how does that standard user handle being in multiple tenants without adding layers of complexity to it.

Take a user signing up to a URL which is dedicated to a single tenant but they already have an account under another one.  We don't store the passwords (that's bad) and we don't want to change their password (as they know it for the other tenant). We can trap that the user exists and add it to both tenant - BUT - how do we convey this to the end user in a way that won't cause issue for you or your tenants?  You could send an email that says "We have found an account which is already linked and registered on this site from XX other site.  You have been granted access to use that account on this site with the same username and password to log on." Which would be OK in this instance but all of the potential places where the account could be changed and updated would need to be worded in a generic way.  E.g. if a company manager changes their password, which would be across all tenants but would require extra text that it had been updated for all of the other URLs too. Otherwise the user would be confused resetting their password every time they logged into each different tenant and changed their password.

**Comment by ericfalcon** [comment]
Good morning.
I have the same problem.
I have a few users who are company managers but need to be able to be a student in another company's courses. These courses cannot be shared with other companies, whether open sharing or closed sharing.
For context, this is an evolution from a moodle3.9 to an IOMAD 4.1 and it was previously possible to be a category manager and a student in another category.

**Comment by turf212** [comment]
This was added as functionality from IOMAD 4.3 on.
