### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by groiso** [iomad/iomad#1835]
I would like to know if I can use any moodle theme or do I have to use exclusively the themes for IOMAD?

**Comment by turf212** [comment]
You can use any Moodle theme, however, you may not get all of the features such as Per company logos (if you are using 4.1+ and the theme uses the standard Moodle logos settings then it will work), per company menu items, and the per company CSS.  This is simply because Moodle doesn't know about companies.   Any Moodle theme can be converted to work with IOMAD and provide all of these features.
