### ISSUE TITLE
Moodle upgrade pending, cron execution suspended

### ISSUE THREAD

**Issue by OliverOPI** [iomad/iomad#1864]
Hi Derick. Have you ever encountered the situation where Moodle cron will stop working if it detects that an upgrade to the base Moodle is available? We are on IOMAD 4.14, and the latest Moodle is 4.2.1+ (Build: 20230707), and cron is whining and complaining that we're not on the latest Moodle code base, which is odd since that's intended.

Why would cron just stop working? Would this mean that cron is not working for all IOMAD installations, since IOMAD is always a bit back from the latest release? Whole thing seems unusual since I'm sure there are many older Moodle code bases out there that need to run properly without upgrading.

How can we get cron working again without upgrading?

Steps to Reproduce
- ssh into the Moodle server and run /usr/bin/php -f /var/www/html/admin/cli/cron.php (adjust path as necessary)

See https://tracker.moodle.org/browse/MDL-43314 and https://duckduckgo.com/?q=Moodle+upgrade+pending%2C+cron+execution+suspended.&t=chromentp&ia=web

**Comment by turf212** [comment]
the IOMAD code contains all of the Moodle code so if you are on IOMAD 4.1 you should be on the Moodle 4.1 code too.  If you want to use Moodle 4.2 ( or any other version) then use the IOMAD version for our repo instead of the Moodle one (as it has it all included and you don't need to do anything else :) )
