### ISSUE TITLE
Users moved from one company to another the records do not transfer. 

### ISSUE THREAD

**Issue by Blacksheeprules** [iomad/iomad#1884]
When users are moved from one company to another the records do not transfer. 

Once a course has been assigned to a company and in progress, users who have been transferred from another company do not show up in the course reports. We found a hack to fix this. Give the user completion of the course in Moodle activity reports, remove that completion, unenroll the user from the IOMAD dashboard. Enroll the user. The user will now be in the company user reports as completed so we cleared the course. The user is now in the reports as 0 % completion. 

Is there a way you can fix this?

Thanks in advance!

Mark

**Comment by turf212** [comment]
Yes - but within the database only at the moment.

If you update mdl_local_iomad_track and set the companyid for the user to be the new companyid then the old records will show up for the user.

The underlying issue is not a technical one rather around who does the data belong to?  The user?  Or the company?  If the user is an employee and the company paid for the courses then who should have access to the records?  Should the new company (who hasn't paid for them)?  I feel this should have a workflow where you can move a user and have the option to include their records.  That way there is the choice of the admin.

**Comment by Blacksheeprules** [comment]
If you update mdl_local_iomad_track and set the companyid for the user to
be the new companyid then the old records will show up for the user.

Is this done from the database directly?

Thanks for your reply.

mark

**Comment by turf212** [comment]
Yes - you need to run some sql in the database - something like - 

update mdl_local_iomad_track set companyid = a where userid = b;

**Comment by Blacksheeprules** [comment]
Thanks,

**Comment by BIGBOSS456-2** [comment]
Hai Anyone can help me I was scammed by a loan company So I want you all to help me get the database And money and we share together because he has cheated a lot pleass help me guys 😭🙏

**Comment by turf212** [comment]
Functionality to move users between companies was added in 43 as part of the ability to have users in multiple companies.
