### ISSUE TITLE
Support Email wrong in IOMAD automailer

### ISSUE THREAD

**Issue by BananaRama203** [iomad/iomad#189]
Assuming I am correct. The IOMAD automailer uses the Core Support email.

However if the the support email is changed from the default support email within the core moodle settings, iomad automailer will pick up the default support email and not the updated moodle support email

**Comment by BananaRama203** [comment]
Apologises for double post. Clearing the site cache doesn't have an effect.

**Comment by turf212** [comment]
Email system should be using the support contact email.  Will check and confirm but this looks like a bug.

**Comment by turf212** [comment]
The issue here is not that the automated emails are being sent from the support user (they are) but that emails which have a senderid set (so when you do something) it sets the from email address to be your email address.   Your main admin account has your details on it so they all come from you.  What needs to be changed is that, if the sender is a site admin, it doesn't set the sender id and it then comes from the support contact details.

**Comment by BananaRama203** [comment]
Make sense. When reviewing can you look into adding the same HEADER used in UserCreate to CourseAllocate/CourseUnallocate.

**Comment by turf212** [comment]
Can you please raise that as a separate issue?  I'm about to push a fix for this original one.

Thanks

**Comment by BananaRama203** [comment]
Confirmed as fixed in the recent email logic change.
