### ISSUE TITLE
Iomad Plugin - Woocommerce not registering users

### ISSUE THREAD

**Issue by ludz007** [iomad/iomad#1922]
Hi There, I have purchased the iomad plugin single license for one year.

I have followed all the steps as per file:///C:/Users/Werk/Downloads/WP-WooCommerce-Setup-Guide-4.1.pdf

When a user buys a course, it is not registering them on my iomad site?

What am i missing?

Ive done everything according to the tutorials.

**Comment by Jonoalt** [comment]
I am having the same issue, did you come up with a solution ?

**Comment by turf212** [comment]
For other finding this issue in search - this could be due to a number of reasons - typically these are:

The purchase hadn't been marked as complete
The product wasn't virtual
The user was created on IOMAD but not assigned to any company due to the auto assignations 
The company didn't have the shop enabled

If you have purchased the plugin we can provide support for you through our helpdesk.  You can use the contact forms on the IOMAD website to start that conversation.
