### ISSUE TITLE
Questions about integrating this function into another moodle website

### ISSUE THREAD

**Issue by WilsonWuu** [iomad/iomad#1927]
Dear developers,

I am a Moodle website developer and I'm very impressed with the product you have developed. I believe it would be a great fit for my website. In the past, I have used local plugins to extend Moodle's functionality. I would like to know how I can integrate your program into my website and if there is a local plugin version available.

I am eager to utilize your product to provide a better experience for my users and enhance the functionality of Moodle. I am highly interested in your technology and innovation and believe it will bring significant improvements to my website.

I would greatly appreciate any guidance or resources you can provide. I look forward to the opportunity to collaborate with you and believe it will be a win-win situation.

Thank you for your time and attention.

Best regards,

Wilson
Moodle Website Developer

**Comment by turf212** [comment]
Hi Wilson,

IOMAD comes with the full core Moodle code so you would just need to switch the core Modole code with the full IOMAD release of the same version (or higher) and then run the upgrade as normal.  We would release it as a a suite of plugins but there are changes to the core Moodle code to allow the multi-tenancy to work - which is why we provide it as a full release with the Moodle code as part of it.  The plugins by themselves would not work.

If you are using git to manage your code base (and you should be :) you can point it at the IOMAD repository and simply checkout the same version of IOMAD as you have Moodle. As long as you don't have a weekly branch you will be fine.  It goes without saying - test this first in a clone of your live site.
