### ISSUE TITLE
Ideas : Hide company selector in header and Inherit parent company custom appearance on creation

### ISSUE THREAD

**Issue by LeonidasFRA** [iomad/iomad#1950]
Hello,

I have 2 suggestions that would be handy for many admins (I guess).

1) You have added a company selector in the header, it's a great feature if the user is used in several companies, however I don't think it's relevant to actualy display it if the user is only into one company. (Maybe add an option to hide it if only in one company)

2) When clicking on "create child company" from the Manage company tab, it be relevant not to only grab the different logos, but also the custom CSS/colors/Custom menu items (and certificate design if it's not already the case).

**Comment by LeonidasFRA** [comment]
Also the restriction based upon being part of a company could also have an option to allow members of child companies to have access to the restricted content. It might make restrictions easier to handle.

In example, since every companies are sharing the same home page, i'm using the restrict access by filtering companies. But anytime I would add a child company I would have to edit each restriction (and it could be source of errors and mistakes).
So having this option my mind would be freed haha

**Comment by dallenk** [comment]
Nested companies don't show in the drop down.  Maybe a flout can be added for that?

**Comment by CesparRes** [comment]
It would also be nice to have an option to hide this header "companymenu" display because in our particular site, it doesnt look good at all.

For now we've simply removed the code from "company_info_popover.mustache" to hide this selector menu -  because it's permanently displayed even when a user is only in a single company.

**Comment by turf212** [comment]
It would be easier to hide it in the CSS rather than changing the code.  So something like:

`.navbar.fixed-top .companymenu{ display:none;} 
`
would work.

Interesting ideas for the company restriction and defaults for child companies when creating them.

**Comment by LeonidasFRA** [comment]
Well, hiding it for everyone will fix @CesparRes problem, but for me it might not be the solution. Since people in the same company might have the need to see the company selector, and others might not. I guess other people could encounter the same issue.

**Comment by CesparRes** [comment]
For us it just looked bad as it was using the wrong company logo (or rather the variation that just didn't look right on the background of the header bar) - also it seems redundant to have it when the user is only in a single company.

I guess more customisation options for it, and to hide it when it's not needed would help.

Will look at adding the custom css to hide it instead of code change though - if only because it's frustrating to constantly put code changes back in at updates 😀

**Comment by turf212** [comment]
This was added in commit 5acec5cdef88ee30b2dbb5bc4519539ec66edc3d from 16th October. Setting was added to the local_iomad_settings plugin to enable/disable the switcher.
