### ISSUE TITLE
IOMAD 4.1 - Clicking on Multi-Tenant Dashboard takes more than 4 seconds to load..

### ISSUE THREAD

**Issue by VFXpro** [iomad/iomad#1956]
With thousands of orgs maybe there is nothing that can be done, but we're wondering if..

1. DB indexes for orgs are in place?  Perhaps, you never came across a user that have thousands of orgs in the system?
2. The query could be optimized?

**Comment by turf212** [comment]
So this is due to the post processing for parsing the tenants for child / parent relationships. How important is the 

My company
- My first child
-- My second child 

formatting for you?

**Comment by VFXpro** [comment]
Good finding!  Do you feel if you would return the list as "Flat" it would be drastically faster? If yes, then go ahead, remove the hierarchical display since it's already offered in the Manage Organizations page anyways as shown here...

![image](https://github.com/iomad/iomad/assets/44643864/46b6a212-735a-41aa-b1fe-b75a5ac5bf4a)

**Comment by turf212** [comment]
I've refactored this so that the (S) is now being added from within the database call rather than by parsing the list of companies.  I've added an option in the local IOMAD Settings plugin to turn off the hierarchies as these were also being parsed after the list was first generated. Added in commit d277a6cbf192701b042be146fa56ae60a9afed77
