### ISSUE TITLE
SAML2-SSO only one identity provider is accepted

### ISSUE THREAD

**Issue by jalapatas** [iomad/iomad#1959]
With iomad using SAML2-SSO from two different Microsoft enterprise applications, it is not possible to have more than one working configuration. 
If you have two configurations with two different IdP entities, only the last one saved works. 
The following error message is displayed:
![image](https://github.com/iomad/iomad/assets/10565946/3c5cc741-c15d-4560-9cba-3ea79b30496a)

**Comment by tom5850** [comment]
As this is a critical issue for us, I have investigated it further and would like to share my observations.

As my colleague described in the last comment, only the last saved SAML2 SSO configuration works.

- Create SAML2 configuration for tenant A and test -> works fine
- Create and test SAML2 configuration for tenant B -> works fine
- test SAML2 for Tenant A -> it fails, giving the error in the comment above
- save the SAML2 configuration of tenant A again without changing anything, test it -> now it works fine again
- test SAML2 for tenant B -> does not work anymore, gives the error in the comment above

In dataroot/iomadsaml2 three files are created when you configure a SAML2 connection. A pem and a cert file, which appear to be static. And an idp.xml file which contains the SAML2 metadata of the last saved SAML2 configuration. Only the SAML2 IDP whose configuration is available in this idp.xml file will work. The other IDPs don't work.

It looks like the part of the code that handles the idp.xml file is missing multi-tenant support. Or are we missing some important configuration parameter?

Any help on this would be greatly appreciated.

**Comment by tom5850** [comment]
Some more details: This error happens only when in the field "IdP metadata xml OR public xml URL" the metadata xml information is entered. It does not happen when the URL is entered.

The reason for this bug is, that the filename of the idp.xml file in "dataroot/iomadsaml2/" is defined by (config.php, line 33 and maybe other places):

$metadataurlhash = md5($idpentity->metadataurl);

If no URL is given but xml data instead, the system seems to take a default value which is the same for all tenants, which breaks the multi-tenancy functionality.

**Comment by turf212** [comment]
Did you find a work around for this?  If this is a single file, and is being overwritten each time - if this were to have a file per tenant ID (using the $postfix variable, would this work?  Something like:

```
// IOMAD
require_once($CFG->dirroot . '/local/iomad/lib/company.php');
$companyid = iomad::get_my_companyid(context_system::instance(), false);
if (!empty($companyid)) {
    $postfix = "_$companyid";
} else {
    $postfix = "";
}

$metadatasources = [];
foreach ($iomadsaml2auth->metadataentities as $idpentity) {
    $metadataurlhash = md5($idpentity->metadataurl);
    $metadatasources[$metadataurlhash] = [
        'type' => 'xml',
        'file' => "$CFG->dataroot/iomadsaml2/" . $metadataurlhash . $postfix . ".idp.xml"
    ];
}
```

Was this what you did (assuming you fixed it)?

**Comment by tom5850** [comment]
@turf212 We haven't fixed it yet, since we have only one client where we must enter the full metadata xml in this field. For all other clients we can work with entering the metadata url, which works fine.
We postponed a fix until we have urgent need for a second client needing this. But I had exactly this solution in my mind.
Let us check it. We will let you know how it went.

**Comment by tom5850** [comment]
@turf212 Your suggested code works perfectly to read the correct metadata xml file. Missing piece is to store the metadata xml file also with the company postfix. 

Function get_file_idp_metadata_file in iomadsaml2/auth.php (line 208) needs some modifications:

```
    public function get_file_idp_metadata_file($url) {
		// IOMAD
		global $CFG;
		require_once($CFG->dirroot . '/local/iomad/lib/company.php');
		$companyid = iomad::get_my_companyid(context_system::instance(), false);
		if (!empty($companyid)) {
			$postfix = "_$companyid";
		} else {
			$postfix = "";
		}		
        
		if (is_object($url)) {
            $url = (array)$url;
        }

        if (is_array($url)) {
            $url = array_keys($url);
            $url = implode("\n", $url);
        }

	if ($url == 'xml') {
			$filename = md5($url) . $postfix . '.idp.xml';
        } else {
			$filename = md5($url) . '.idp.xml';
		}
        return $this->get_file($filename);
    }
```

**Comment by tom5850** [comment]
@turf212 We tested this further. The code update to store the metadata file in classes/auth.php is still missing in the 4.3.9 release. Maybe for good, because I have done a mistake. This would be the correct code:

```
    public function get_file_idp_metadata_file($url) {
        // IOMAD
		global $CFG;
		require_once($CFG->dirroot . '/local/iomad/lib/company.php');
		$companyid = iomad::get_my_companyid(context_system::instance(), false);
		if (!empty($companyid)) {
			$postfix = "_$companyid";
		} else {
			$postfix = "";
		}
		
		
		if (is_object($url)) {
            $url = (array)$url;
        }

        if (is_array($url)) {
            $url = array_keys($url);
            $url = implode("\n", $url);
        }

        // IOMAD
        $filename = md5($url) . $this->postfix . '.idp.xml';
        return $this->get_file($filename);
    }
```
    
But doing it this way in combination with the code you have suggested to fetch the correct metadata from file implies that all IOMAD users must save the SAML2 configuration of their tenants again.

In the previous version, the metadata file (when using the metadata URL), was something like this:
- [Full IOMAD domain of tenant].com.xml, e.g. tenant.iomad.org.xml

With the code changes, it will be:
- [MD5 hash of SAML2 metadata URL]_tenantid.idp.xml, e.g. bcc1239fca41f63927ad6de624abcd73_99.idp.xml

This code change will break all current SAML2 configurations. But I think it makes sense to update the code this way. It's not possible anymore to conclude from the file to the client without having further information about the tenantid, which adds more security. Just my thoughts.

I leave the final decision up to you.
