### ISSUE TITLE
Clone new course do not automatically assigned to company

### ISSUE THREAD

**Issue by huy-nm** [iomad/iomad#1980]
When cloning a new course, select a company for Course category. However, when finish cloning, the course is not assign to that company. We need to manual assign it to company. I wonder if this is a bug.
This is from IOMAD 403 STABLE

**Comment by turf212** [comment]
Correct - this is because the Moodle functionality - which you are using here - doesn't understand about companies.  There has been an option for company designated courses (courses which the company manager has created them or have been given control of) for the company manager/admin to cone the course and keep it in the company.  This is in 4.3+ and was added under commit 30afcba9d21a9e25c8c58bf78eea3e9eeaca25e4
