### ISSUE TITLE
Vaunrability got me hacked

### ISSUE THREAD

**Issue by ludz007** [iomad/iomad#1983]
Hi There,

This morning, when i tried to login to my site... it was hacked.... all files in public_html were changed and deleted... just letting you know :/

Il have a look into what could have caused this

**Comment by turf212** [comment]
This would have been bad permissions on your webserver files. Typical types of attack are adding something to the crontab of the user who runs the webserver processes or, if there is a vulnerability in Wordpress and it's installed on the same server under the same system account then that can also cause issues.

Hopefully you were able to recover and worked out what the issue was.  I'll close this.
