### ISSUE TITLE
REST API calls using block_iomad_company_admin_edit_licenses fail due to code error in externallib.php

### ISSUE THREAD

**Issue by CesparRes** [iomad/iomad#1996]
Upon attempting to update a license that exists, I get receiving the error:
`REST exception handler: Error writing to database Debug: Column 'licenseid' cannot be null\nINSERT INTO mdl_companylicense_courses (licenseid,courseid) VALUES(?,?)\n[array (\n 0 => NULL,\n 1 => 4,\n)]`

Trying to edit a license that does not exist, returns the expected "License id=X does not exist" error.

Upon digging into the code: 
```
            $id = $license['id'];

            // does this company exist
            if (!$oldlicense = $DB->get_record('companylicense', array('id' => $id))) {
                throw new invalid_parameter_exception("License id=$id does not exist");
            }


            // Deal with course allocations if there are any.
            // Capture them for checking.
            $oldcourses = $DB->get_records('companylicense_courses', array('licenseid' => $licenseid), null, 'courseid');
            // Clear down all of them initially.
            $DB->delete_records('companylicense_courses', array('licenseid' => $licenseid));
            foreach ($license['courses'] as $course) {
                $DB->insert_record('companylicense_courses', array('licenseid' => $licenseid,
                                                                          'courseid' => $course['courseid']));
            }
```

We see that the DB inserts are attempting to insert $licenseid which does not appear to exist.

I believe the correct fix is either
```
            $licenseid = $license['id'];

            // does this company exist
            if (!$oldlicense = $DB->get_record('companylicense', array('id' => $licenseid))) {
                throw new invalid_parameter_exception("License id=$licenseid does not exist");
            }
```

or changing instances of $licenseid to $id instead.

With that being said, I believe this misses something still as the response from server after the request claims the response is invalid, but the update still goes through

**Comment by turf212** [comment]
We've made some changes as to how that function works in ca488bc54bbd372d0433482bc1143854983b7ae3 as the way it was handling the child license on parent license change wasn't good.

Path had been:

Update parent license to add/remove a course
child license get's all courses removed and all courses add to it - even if it only had a subset

Changed this to:

Update parent license to add/remove course
If license is a Program - all child licenses are updated to match this and amounts or available/used/etc are updated to be correct
If license is an ordinary one, update child license to remove any courses which are no longer in the parent license - otherwise leave it alone.

In saying that - you are 100% correct that the id variable is changing from $id to $licenseid so it should be $licenseid throughout.
