### ISSUE TITLE
block/iomad_company_admin - Not showing on users with permissions unless i set admin company (mdl_company id=0)

### ISSUE THREAD

**Issue by ludz007** [iomad/iomad#1998]
Hi There,

I have a weird problem i cannot seem to fix.

I have updated my iomad installation.

After that, i had an error where my users could not go to "view courses" unless i changed my first company to id=1, but when doing so, i have created another problem.

The "manager dashboard or "/blocks/iomad_company_admin/index.php" is blank on their side, even though they have the permissions setup as per their roles.

I dont know what to do, if i change the value in mdl_company id=0, i cannot even login as admin - error is as 
![image](https://github.com/iomad/iomad/assets/52195007/92aa1363-0652-4000-b2b6-ceb2423b58ce)

can someone please please advice?

Regards

**Comment by ericfalcon** [comment]
Hello
Obviously this is a field type problem.
A Bollean field is expected (yes/no) and there is a string type field (string)

**Comment by turf212** [comment]
The ID's in the company table should be incremental - never a good idea to just change them as they will be tied into many other tables as a foreign key.

I suspect this was a bug and has been fixed since as this version has been on a number of environments clean and upgraded and none are having this issue.  I hope you were able to resolve this.
