### ISSUE TITLE
Does the latest IOMAD not support Postgres?

### ISSUE THREAD

**Issue by asamolion** [iomad/iomad#2001]
I recently upgraded my IOMAD installation to 4.3+ and got the error 

![iomad postgres 2024-06-13_23-37](https://github.com/iomad/iomad/assets/14261053/5d07e307-7f63-4927-b0f9-d76b943aafab)

It is because of the `IF` statement from MySQL/MariaDB not being Postgres compatible.

Does IOMAD not intend to support Postgres in the future?

**Comment by screamwork** [comment]
good question! anyone? i tried a few tools to get the data out of PG into MySQL, but without luck!

**Comment by keithkhl** [comment]
https://github.com/iomad/iomad/issues/2026

Just added another request, probbly the same one. If this kind of basic bug reported in June has not been dealt with in 3 months, I think it is better to go on with multiple Moodle installations. This is kinda shame, unless IOMAD decides to not support PostgreSQL.

**Comment by keithkhl** [comment]
Instead of complaining, it is always better to fix a problem by oneself. Below is a how to guid for PostgreSQL I hope the IOMAD team also use it.

The trick is to replace IF to CASE, as PostgreSQL does not use IF, and fix the squeries accordingly.

In your Moodle/IOMAD folder, find the function '/var/www/moodle/local/iomad/lib/company.php'.
Then, search for 'SQLIF'. There are 4~5 occurances in total.

I changed the variable SQLIF to SQLCASE by this -> $SQLCASE = "CASE";
and, changed queries  $SQLIF (suspended=0 -> $SQLCASE WHEN  c.suspended = 0 ......
Mkae sure you remove ) at the end of the query. If troubled I think ChatGPT will do the fix for you.

**Comment by dallenk** [comment]
@keithkhl I don't think that was an appropriate comment..  most of us are not experienced making changes like that.   If/when people make changes to local code and later try an update with git it is going to throw errors and fail.   there are many bugs that have been reported, and several users have pull requests pending for everyone to benefit, but they go unchecked.   I have bugs reported that go back almost a year now, and unfortunately I don't know nearly enough about php to fix them myself, and I'm not trusting AI to fix the code for me.

403 is absolutely not stable, so that is also problematic for people new to IOMAD.

the fix you suggested is helpful, but posting issues here shouldn't be viewed as complaining IMO..

**Comment by keithkhl** [comment]
@sgvfr I agree with you in every aspect. I just shared quick workaround for urgent needs. The code is IOMAD's product, not mine, so I wasn't going to commit my extended version code for cases where database name value is for MySQL/MariaDB/SQLite and PostgreSQL separately. I am as mad as you that this kind of simple and basic fix has not been handled by IOMAD for months. I find a lot of bugs over a day of testing already, and I wonder if I should trust IOMAD for long-term. 

But for now, as much as I do not trust LLMs, for that piece of code, I have confirmed that it gives me the right temporary fix, so feel free to rely on ChatGPT (or any similar sort). By FTP, go to your IOMAD's folder, and find the troubled file in ~/iomad/lib/company.php

Use look-up to find SQLIF occurances. Copy the entire block of that code to ChatGPT and ask to convert to PostgreSQL. I made the file not rewritable for now, as I do not like another git commit overwrites my quick fix.

**Comment by jeroenhabets** [comment]
I stumbled upon this project and checked its PostgreSQL support and found this issue (https://github.com/iomad/iomad/issues/2001)

In this day and age there is no need to use non-standard IF(...,...) and IFF(...,...) as all Moodle supported databases properly support CASE statements nowadays. Furthermore SELECT COUNT(*) should never return NULL.

NOTE: I'm not running iomad myself so this patch is _completely_ untested. I am providing it as it's probably easy for you to just quick apply it and giving it a spin. And keep users from abandoning the best open source db.

**If @asamolion, @screamwork, @keithkhl, @sgvfr or anyone else finding this issue is able to test https://github.com/iomad/iomad/pull/2031, please do and comment your findings there.** (https://github.com/iomad/iomad/pull/2031 and I'll try to fix any issues you encounter)

**Comment by dallenk** [comment]
I will patch and test on my sandbox.  Thank you

**Comment by turf212** [comment]
I've added the patch to the code as it was a better solution that the one I'd put in place to fix MS SQL Server that unfortunately broke PostgreSQL.

**Comment by support-accellier** [comment]
@turf212  this change is creating a **CRITICAL ISSUE** as it is stopping normal user to login into the system since there is code around line 253 and 263 in function get_companies_select which is still using $SQLIF

$companies = $DB->get_records_sql_menu("SELECT DISTINCT c.id, $SQLIF (c.suspended=0, c.name, concat(c.name, ' (S)')) AS name, cu.lastused
