### ISSUE TITLE
Unenrolled users still showing in Course Summary and User reports

### ISSUE THREAD

**Issue by mikeaveli007** [iomad/iomad#2028]
Seeing users that were unenrolled from a course showing up on the course summary report and the user report.  Is there a way to clear that out?  I noticed there is sometimes an action to "purge", I saw this as an option a couple of times and that removed the record. but it doesn't always show.  I see "clear course" but that doesn't remove the user from the reports.  Is there any other way to remove users from those reports?

**Comment by turf212** [comment]
The systems keeps records of everything in the reports which is why it can allow for users being removed and re-enrolled in the same course over and over again for re-certification.  If you want to remove the records from the users reports you can purge them from either the course report page or the users report page.  Make sure to turn on editing on the page first and then you can use the Purge entry option.
