### ISSUE TITLE
company_users_licenses_form.php have to unallocate twice to unallocate error

### ISSUE THREAD

**Issue by BananaRama203** [iomad/iomad#204]
Hi I got a issue that I am hoping you can confirm as a bug within Vanilla Iomad on the company_users_licenses_form.php page. The issue I am having is when you try to unallocate course from a user you have to unallocate the course twice for it to actually unallocate.

i.e.
Select user
Go to company_users_licenses_form.php
select license
select course and click unenrol
(page refreshes)
Course is still there and +1 to the license count
Select the course again, click unenrol
(page refreshes)
Course is unallocated and + 1 to the license count.

(Apart from having to unenrol the course twice it also adds 1 to many to the license)

I have got a custom company_users_licenses_form.php page but it's mainly formatting and shouldn't effect the functions of the page. If someone can replicate this issue in their IOMAD and let me know if this is indeed a issue I would be grateful. Otherwise I will have to revert to the old version until I work out what is causing the grief.

Thanks
![company_users_licenses_form.php](http://i.imgur.com/qZhb36c.png)

**Comment by turf212** [comment]
This should actually be doing a count for the numbers used rather than accepting that the number in the license record is still correct which is what the other license allocation screen does.

I've not been able to replicate the issue where it doesn't actually not remove the license course.  What browser are you using for this?  (I'm using Chrome)

**Comment by BananaRama203** [comment]
Confirmed as fixed in commit f85cf2140e38d44d96076be1cc85118b3329e275
