### ISSUE TITLE
IOMAD 4.3.8: creating child company is broken

### ISSUE THREAD

**Issue by tom5850** [iomad/iomad#2044]
I go to "Manage companies", search for my parent company, and then click on "Create child company".
When I then submit the form (company_edit_form.php):
1. After first click on "Save new company" nothing happens.
2. After second click the company is created, but I stay on the same screen (company_edit_form.php) just with empty fields.

The company created is not a child of the selected company, it is created as a new parent company.

**Comment by tom5850** [comment]
Such a false "child" company can not be deleted anymore.
(Child) companies created before upgrading to 4.3.8, can be deleted though.

**Comment by turf212** [comment]
The forms weren't working well here and they were redirecting to the wrong place - meaning that the company was being created but it wasn't telling anyone this.  This has been reworked so that if the parent company is updated on the company creation then the company isn't created and then re-directed to the same form.  Form is refreshed and current data is stashed and loaded to it instead.
