### ISSUE TITLE
Error when bulk uploading users within IOMAD

### ISSUE THREAD

**Issue by dcraven002** [iomad/iomad#2088]
I am trying to bulk upload users within IOMAD within a Company (Users > upload Users) but I am receiving this error.

IOMAD version: 4.3.8 (Build: 20241007)

![Screenshot 2024-12-04 at 17 01 22](https://github.com/user-attachments/assets/da9b8d23-cfcd-4750-8442-a31c8e9342b0)

The example file import I am using is the below
```
username,email,firstname,lastname,course1,role1,group1
john.doe,john@example.com,John,Doe,course101,student,atlas
jane.doe,jane@example.com,Jane,Doe,course101,student,atlas
```

I am able to upload users and enrol them in bulk using this file but they are only enrolled on the Moodle side outside IOMAD, so  the issue is they don't get enrolled into the course on the IOMAD side.

**Comment by turf212** [comment]
That file has been changed a fair bit since 4.3.8 was released. I thought it might be the group1 field but I've just tested with columns
username,firstname,lastname,password,course1,role1,group1

and everything went through.  The preg_match call is checking for dates on each of the values in the columns after checking if the column has a value.

I suspect that this may have already been fixed.  There will be a new point release from Moodle on Monday for 4.3.9 which will be pushed to our repos then.  You could either update now (and again after Monday) and check or just wait till Monday and check.
