### ISSUE TITLE
Sending email from IOMAD for users enrolled to courses

### ISSUE THREAD

**Issue by debdeepdas** [iomad/iomad#243]
Hello,
I am using IOMAD 2.7.3 for my internal training as I want multi-tenancy. I want to send email to users when they are enrolled for a course. I am using manual enrollment. I see entries getting created in the email table but emails  are not going out. I can send email from the site using the default email functionality though. The email table has sender id as NULL. Is that a problem and how do I fix that. The cron job at ./admin/cli/cron.php is running.

Please help me.

Thanking You for your help 
Warm Regards
Debdeep

**Comment by debdeepdas** [comment]
When I ran the local/email/cron.php from the browser, I see that emails are going out. So there is no issue with the email sending. How do I include this cron to be run by server cron under admin/cli/cron.

Regards
Debdeep

**Comment by debdeepdas** [comment]
I could fix this by using wget. Thanks

**Comment by ehuggett** [comment]
Did you accidentally re-open the issue? Since it's still open I'll add my 2 cents

The documentation should be helpful, there is a lot of information about how to do this https://docs.moodle.org/29/en/Cron . I would recommend running the script directly with the php cli rather than calling it indirectly with wget. 

Also Note as of Moodle 2.9, the cron job can no longer be run from web by default so your wget method will most likely stop working when you upgrade to a IOMAD version based on Moodle 2.9 (the most recent IOMAD is currently based on Moodle 2.8).

Regards
