### ISSUE TITLE
No obvious way to know what username Iomad generates

### ISSUE THREAD

**Issue by thepurpleblob** [iomad/iomad#257]
When 'manually' creating users, Iomad appears to create a username based on the first name followed by an index number. However, short of searching for that user after creating it, there is no way to know the username that was automatically generated. So, creating 'one off' manual users is effectively broken. 

There should, at least, be a page confirming that the user was created and stating their generated login details.

**Comment by turf212** [comment]
When a manger creates a user with uknown user log in details (i.e. if they get the system to send an email with the password) they also receive the email that the user gets with these details.

Additionally, in 3.0 there is now the option to use the email address as the username instead of the automatically created one.
