### ISSUE TITLE
Reduce size of edit boxes in 'Manage Iomad course settings' page so the form fits

### ISSUE THREAD

**Issue by thepurpleblob** [iomad/iomad#263]
The edit boxes are too wide so the form ends up blowing out of its container. Wouldn't hurt to make them smaller.

**Comment by ehuggett** [comment]
I had to resize the window to see this (1920x1080 22" Monitor) but it also seems to happen on various other forms when using the iomad theme. For example "Site administration / Appearance / Themes / Theme selector" also breaches out of the container when the window width is reduced too far.

When using the "clean" theme a horizontal scrollbar is displayed when the window width is too small and it never breaches the container.

To me it seems the root cause of this is the iomad theme and not the "manage iomad course settings" form.

However, reducing the width of "Training expires after (days)" / "Days to email before training expires" / "Days to email after if not complete" would avoid the need for horizontal scrolling in some cases.
