### ISSUE TITLE
Developer documentation

### ISSUE THREAD

**Issue by symball** [iomad/iomad#293]
I've just started using IOMAD and am poking around under the surface. There will be extra reports and functionality I want to integrate and wondering whether there is any developer documentation available for download, there's a distinct lack of it.

If there isn't, I propose creating a set and having it present in the repository or at least creating a wiki for it. I feel Moodle as a whole would lose quite a valuable contribution if development on this were to suddenly stop and I wouldn't want to waste all the good effort you've put in!

I've started compiling my own documentation and am sure others could benefit and contribute to this cause. There's a LOT of demand for multi-tenancy Moodle and the only real (fork based) competitor is Totara.

**Comment by turf212** [comment]
This is something which has been on or long term todo list but actual real paid work keeps getting in the way.  I'm updating this as an enhancement as it would benefit everyone.

**Comment by ehuggett** [comment]
I think it would be nice if the  "Moodle Docs for this page" links visible to administrators in the page footers also worked for iomad documentation .

The moodle documentation links simply link to `http://docs.moodle.org/<version>/<language>/<path of the current page>` , if the iomad documentation was organised in the same fashion then it would be possible to redirect from the iomad documentation (or link from) to the moodle docs if no documentation for that pages exists in the iomad docs.

Or perhaps it would be cleaner to work out how to 'override' the help url for a page (so that iomad pages link to docs.iomad and the unmodified moodle pages link directly to docs.moodle).

If the documentation is user editable I think I would find the time to contribute at least a few pages.

**Comment by turf212** [comment]
I've started a WIki for this and will add it to the www.iomad.org website once I have some content.  The plan would be to over-ride the docs link although the links for the documentation for the Moodle parts should remain the same.

**Comment by saadzaman** [comment]
Hi Guys, 

Is there any update on the documentation for developers ? I cant find a wiki still

**Comment by jgdk** [comment]
Hi Dereck, It would be much appreciated, when you can open up for the Wiki so there can be more implementors, who could contribute with the content to it...  That would be the lease we could do :-) Thank you.
