### ISSUE TITLE
Company Themes

### ISSUE THREAD

**Issue by andrepazleal** [iomad/iomad#32]
Just installed IOMAD Moodle 2.5.4+ (Build: 20140117).

Configure some company and define some different themes for each one of them, still after that when login is a user for that company it remains the main theme defined in the admin account. It´s only me?

**Comment by turf212** [comment]
Can I ask if you are logging in as the other company user using the "log in as" link or are you directly logging in as that user?

Thanks

**Comment by andrepazleal** [comment]
Hi there, yes I´m logging as the user itself. By the way, nothing to do with the topic, but we´re ready to implement Moodle here at our compny, today we´re using a LMS service that´s been givi´n us a huge headache because of the many functions that they have develop, almost half of them we dont use.
My question is can I merge the moodle instalattion with your guys installation, or if we do that nothing will work?
My question of course it´s because we want to have your multitenancy with the updates from the moodle team, joining both of the worlds, by the way great job. I´m a 3d generalist, graphic, interface, motion designer, work with JS, CSS, if you guys need any help on the project check me in by email, I would love to help you.

**Comment by turf212** [comment]
We have, at least, got to the bottom of why this is working.  As a work around (not a great one but at least temporarily) if you turn on the theme designer mode it will start to display the changes for the company as expected.  The issue is that the company CSS is interpreted and the changes are being cached before the company parts are being being added.  We are working on a fix at the moment.
