### ISSUE TITLE
Show (Manage) Departments in Alphabetical order

### ISSUE THREAD

**Issue by canyasa** [iomad/iomad#347]
Hi Everyone,
How can I show departments in alphabetical order on Manage departments page(company_department_create_form.php) ?

Thanks!

**Comment by turf212** [comment]
It comes from the get_subdepartments() function in the local/iomad/lib/company.php class.  If you change the code so that it sorts on department name in the DB call then this should return what you are looking for.  I.e. top level will be sorted then next level will be sorted within each top level and so on.

**Comment by canyasa** [comment]
I didn't get that part,
$DB->get_records('department', array('parent' => $parent->id)) (this?)

If it is not that long, could you provide me the code and the part that I need to change, please?

**Comment by turf212** [comment]
this has been superceded by the new department picker.
