### ISSUE TITLE
Demo Site

### ISSUE THREAD

**Issue by kscallan** [iomad/iomad#399]
I really like the concept of lomad and would like to try it out for my next project; however, I am having a few issues with navigation.  Some of the fonts are distorted making it difficult to navigate and the logo seems to be formatting incorrectly.  Perhaps this is just a learning curve on my end. See attached.
![example](https://cloud.githubusercontent.com/assets/23339786/20103938/e4fb377a-a599-11e6-8881-81d53472d227.png)

**Comment by turf212** [comment]
You can change the font sizes in the custom CSS box for the theme if they are too small.  something like:
.iomadlink {
    font-size: 14px;
}

which will increase these fonts to 14px.

If the logo is too large then best solution is to reduce the dimensions of the image you are using so that it doesn't cause issues on the page.
