### ISSUE TITLE
The e-commerce block has not been configured...

### ISSUE THREAD

**Issue by thepurpleblob** [iomad/iomad#413]
...this message could quite easily link you to the relevant settings page to set it up.

**Comment by thepurpleblob** [comment]
The bootstrap alert markup is wrong for this message too (escaped quotes are not required)

**Comment by elreydetoda** [comment]
@thepurpleblob it looks like with commit 78787b0ea145c241a65b2d838087009614803bc2 that it isn't properly rendering the space between `alert` and `alert-danger`. 
the files that might be affecting (don't know because I am not intimately familiar with the app) are
https://github.com/iomad/iomad/blob/78787b0ea145c241a65b2d838087009614803bc2/blocks/iomad_commerce/courselist.php#L97 or https://github.com/iomad/iomad/blob/78787b0ea145c241a65b2d838087009614803bc2/blocks/iomad_commerce/block_iomad_commerce.php#L46

this is what it the code looks like on my iomad site
![image](https://user-images.githubusercontent.com/10230166/47434445-928fb280-d770-11e8-8f32-4760788ab0de.png)

and the link for `settings` area isn't rendering either
![image](https://user-images.githubusercontent.com/10230166/47443522-801e7480-d782-11e8-9f55-b5a0b9f4ae3d.png)
