### ISSUE TITLE
[Question] IOMAD Company Deletion

### ISSUE THREAD

**Issue by richard0096** [iomad/iomad#424]
Is it possible to delete a company, currently I only see the option to suspend rather than delete.

**Comment by turf212** [comment]
There isn't at the moment.  It's been a long standing requirement and one we are gradually working towards.  The issue is what do we do with the data/courses/users and so on.  What if they are shared courses?  Moodle technically doesn't delete anything, just marks them as such.  For more see #33 

(closing this as duplicate)

**Comment by arryola** [comment]
I've been looking for this solution but to be frank i agree with you. its better to suspend than delete in the off chance that you;ve mistakenly removed something you arent supposed to. 

Love all your hard work its much appreciated!
