### ISSUE TITLE
Company admin can't access course setup with enrolment method license

### ISSUE THREAD

**Issue by delvon** [iomad/iomad#499]
I have created an IOMAD and set it up as closed sharing with license. 
Is the company admin not supposed to be able to login and access this course or do I have to allocate a license for them as well?

I tried both ways and still getting the infinite loop which ends up with a memory limit error. I tried without  allocating a license on the course for the company admin and also tried without any license being allocated. How do I give access to a company admin on a course (the license enrols you as a student).

Regards,
Delvon

**Comment by turf212** [comment]
That is correct usage.  The thinking is that the license courses are bought and paid for from the site admin for use within the company.  Why would the company manager get free access to the course?

**Comment by delvon** [comment]
Thanks for that.
I now understand this. The company manager can be assigned from the IOMAD dashboard so they can perform their IOMAD functions but if we wanted to give a user the Client Course Editor then we would have to use the normal Moodle assignment to do that.

**Comment by pm-tatiana** [comment]
it doesn't make sense to me @delvon 
I am having a related issue.
Usually when I have a course that's closed shared, not licensed. I assign the course to the company I want and the company manager (CM):

1. Can see the course in the list of available courses or "my courses"
2. CM gets enrolled as Company manager and Client course access and linked to a specific group with same name as the company http://prntscr.com/eta2c0 - This is wonderful because it allows segregation of data and allows me to modify permissions on the company manager and client course access roles so that company manager can check the grades only for those users that belong to his own company (same group).

When the course is **closed shared and licensed**, however,  it doesn't work as I need it to work.
When I, as Site Admin, assign a closed shared licensed course to company A, the company manager is not able to see the course listed in the courses available to the company. I understand that's because all of the enrollments methods are disabled when a course is licensed. This causes the CM not being enrolled into the course as usual (enrolled as Company manager and Client course access). 

the process instead, is that, as Site admin, I need to go and create a license for the company A and allocate the course to the license. 
I thought that, If I wanted the course to be visible to the CM, I have to allocate him a license. That's fine. I can live with that BUT, that's not the case. Even when I allocate the CM with a license, the CM user CAN'T see the course in the list of available courses. 

Do you have any suggestion regarding this?
