### ISSUE TITLE
Category --- View More link returns error

### ISSUE THREAD

**Issue by watcanz** [iomad/iomad#524]
Site is 3.1.6.

Site has six categories. Five show on the front page with a link for "View More".  When student user clicks on View More, site returns error : Coding error detected, it must be fixed by a programmer: moodle_database::get_in_or_equal() does not accept empty arrays

Logging in as Admin User shows all of the categories with no "View More" link.

**Comment by watcanz** [comment]
Bump

**Comment by turf212** [comment]
How are the categories set up?  The navigation should be stripping out categories which the user doesn't have any access to.  E.g. those which belong to another company.  If you have removed categories from the site by hand then you could have run into a data issue because of this.

Put the site into full debug mode (site administration -> Development -> debugging and select full developer and display errors).  What is the error message being displayed?

**Comment by watcanz** [comment]
Our client stopped using IOMAD last year, so we do not have the site any longer.
