### ISSUE TITLE
Iomad reports

### ISSUE THREAD

**Issue by MathiasLarsson** [iomad/iomad#53]
Hi!
I wonder why I don´t get any information under the iomad reports. Can anybody explain how to setup a course to get all the needed info under "Complitation report by course":
Course name     Number of users     Not started     Still in progress   Completed

And
Firstname / Lastname    Email address   Department  Date enrolled   Status  Date started    Date completed  Final score 
Has it someting to do with the "grading"? Any easy solution?

**Comment by turf212** [comment]
Do you have users in the courses which have performed some tasks and received a grade and completed the course?  Is completion turned on for the course?  If you have undergone some of this with test users then you will need to check that the cron is working so that the appropriate information is calculated by the system.

**Comment by MathiasLarsson** [comment]
It seams like the cron´s not working corectly! I tried to manually run the cron-job and after that some result was shown under the report section. The status of the course report has som other small problems (maby not connected to IOMAD) it says "not started" and theres no dates för start/stop. Do you know how to fix a working cron-job?

**Comment by turf212** [comment]
Have a read of here - http://docs.moodle.org/26/en/Cron  It explains how the cron is set up.

**Comment by MathiasLarsson** [comment]
Thanx alot!
