### ISSUE TITLE
Courses are not shown in the shop

### ISSUE THREAD

**Issue by thepurpleblob** [iomad/iomad#58]
When a course is added to the shop it does not appear in the shop (via the eCommerce block)

**Comment by thepurpleblob** [comment]
It turns out that the courses have to be 'open shared' in order to appear in the shop. This isn't at all obvious. Possibly add a warning in the eCommerce admin lists to note that a course will not be shown in the shop because of its sharing (or something)

**Comment by turf212** [comment]
The shop is set up to show courses which are available to that company or, if you are not tied to a company, globally shared courses.  The admin account isn't tied to a company so will only see globally shared courses.  Will update this so that site and client admins can see all of the courses in the shop.  Additionally a standard user should be able to purchase blocks of licenses.  Adding in a check for company_manager instead.
