### ISSUE TITLE
Incorrect final score in "Completion report by course"

### ISSUE THREAD

**Issue by semteacher** [iomad/iomad#580]
IOMAD Completion report by course has displayed final score in wrong format:
https://www.screencast.com/t/3S1nrN1FRmet
Settings to repeat this bug:
- course with multiple quizzes. Quiz max grade should be large (100 in my case)
- course grade sets to being displayed as PERCENTAGE.
So, in this case, report should display final score as 174 (no percentages) or relevant percentage score 87%:
https://www.screencast.com/t/Zx7Zwv9V6y7r (view from course grades report)

**Comment by turf212** [comment]
The scores for the reports are beng pulled from the grade_grades table for the course item for the user.   It's using the finalscore column for this value.  What does your grade_grades table have for the user above?   If this is the same as the report is showing then we need to change the reports so that any additional weighting (as you have) is being captured.   If you can give me the whole row for the affected users it would be much appreciated.  (course item only)

**Comment by semteacher** [comment]
For selected user in given course grade_grades table row really contain summary score (174). Score is correct. But! I repeat my last sentence above:
"report should display final score as 174 (no percentages) or relevant percentage score 87%:"
Actually, I see 174% that is wrong.
So, I expect some correlation - if sum grade displayed - than - no %... If % - than - same value as in  course`s "Grader report"

**Comment by turf212** [comment]
This is due to the grade amalgamation settings within Moodle.  You may need to change your default grade type to simple weighted mean of grades to prevent you getting > 100%.
