### ISSUE TITLE
IOMAD Documentation / Guide

### ISSUE THREAD

**Issue by teddielong** [iomad/iomad#693]
Is there a detailed guide somewhere that I haven't come across?  It would be great if there were such a thing (or if there's an experienced IOMAD'er who would perhaps be able to provide adhoc advice?).

**Comment by ndalpe** [comment]
+1 this request. 

Especially how to migrate an existing Moodle Site to Iomad.

Thank you

**Comment by dbrooks312** [comment]
+1 this request.

Setting up multi-tenancy and interactions w/Moodle course categories.

Thank-you!

**Comment by anshuljain11** [comment]
Hi Team,
Does have aby documentation how to migrate existing Moodle website to IOMAD ?? Please let us know..
This is basic requirement for everyone because we can't install again everything and migrate manually if we have lots of users and courses.

Also if it is having paid service also let us know.

Thanks
Anshul

**Comment by anirudh74** [comment]
+1 Can someone help me out with migration

**Comment by turf212** [comment]
knowledge base is on iomad.org.
