### ISSUE TITLE
Manage departments duplicates select but only one works

### ISSUE THREAD

**Issue by thepurpleblob** [iomad/iomad#71]
Manage departments has both a drop down box and a list of select box. Both show identical information. However, only the select boxes do anything.

**Comment by thepurpleblob** [comment]
![screen shot 2014-04-12 at 12 10 58](https://cloud.githubusercontent.com/assets/664139/2687078/3fabc312-c233-11e3-8767-555be87fe95c.png)

**Comment by pm-tatiana** [comment]
Hi @turf212 and @thepurpleblob 

I think this is a bug instead of an enhancement. Yes, users can just use the select boxes but then why having the dropdown? that is confusing for my end users and. 
It would be good to hide/delete the drop down box from the first view http://prntscr.com/c09u2d

Also, when I click on the "create department" option here: http://prntscr.com/c09v8e
Next screen shows the dropdown and I think it is kind of a filter or a way to tell the system where are we creating the department: http://prntscr.com/c09wew

The "edit department" as well as the "Delete department" options only work with select boxes.

When are you guys fixing this?
