### ISSUE TITLE
clientadministrator can not edit users

### ISSUE THREAD

**Issue by tzumtobel** [iomad/iomad#711]
When I give a clientadministrator the right to create users, he can not edit nor delete those. Admin can. Error code is

Debug info: 
Error code: invaliduserid

Stack trace: 
line 503 of /lib/setuplib.php: moodle_exception thrown
line 85 of /blocks/iomad_company_admin/editadvanced.php: call to print_error()

If a clientadministrator is not intended to create users, who should do it?

**Comment by turf212** [comment]
This is failing the check that the currently logged in user is able to edit the target user.  It checks the following:
- The manager's company matches it to the target users company
- The manager is assigned to a department which the user is under
- The manager account is defined as a manager in the company.

How did you create your manager user?  Did you simply give them the role in the system or did you assign them as a manager using the Iomad dashboard or when you created that user?

**Comment by tzumtobel** [comment]
I checked the given requirements

- The manager's company matches it to the target users company
yes
- The manager is assigned to a department which the user is under
no, because there are no departments. Ist this necessary?
- The manager account is defined as a manager in the company.
yes

We created the user using the iomad dashboard.

We tested it again with the use of departments. Everything works great. Why is there a need to generate a department? Wouldn't´t it be better to use ist without departments?

**Comment by turf212** [comment]
The departments are there to allow for company hierarchies to be created.  There is always 1 department created when a company is created (with the same name) which is where all of the users are stored unless you create more departments.  The main benefits for departments is so that managers only get to see the users they are responsible for.  There is a department manager role for this which allows a manager to manage the users under their branch of the organisation tree.
