### ISSUE TITLE
How to upload users from different departments in one csv file?

### ISSUE THREAD

**Issue by actXc** [iomad/iomad#773]
A larger organisation with many departments wants to upload users with a csv-file. The users are in many different departments.
How to write the csv-file?
Does "iomad_sync_department" and "iomad_sync_institution" really sync in both directions, or does it only fill the user fields "company" and "defpartment" if empty?

**Comment by turf212** [comment]
You need to add a column called department in the CSV file.  The department needs to exist first.  It uses the shortname for the department.

Syncing of institution and department is from the Iomad data to the user profile data only.  Changing the profile data will result in it being overwritten.  The purpose for the sync is to allow for conditional access via profile fields within courses.

**Comment by teddielong** [comment]
This is really useful, thanks.

Where we have a company already set up (with users having department profile field data but no IOMAD departments set up) - what is the best way to now set up so these sync?

E.g. should we create the departments for the company is IOMAD and the reupload the csv so that it syncs?

**Comment by turf212** [comment]
set up the local iomad setting to sync the profile department name to the company department name.
