### ISSUE TITLE
I IOMAD Dashboard adding a new user profile field that is required locks admin user out of the IOMAD. 

### ISSUE THREAD

**Issue by Markrico** [iomad/iomad#842]
Hi folks,

I have IOMAD with Moodle code 3.3.3 (Build: 20171113)

Using the IOMAD dashboard tool Company Management > Optional  Profiles, I created a new user profile field with text input and made it required. It took me to my profile to input the data. No matter what I put into the text area, when I hit save, it would disappear and expect it again. I could not leave the page. I logged out and then back in, to be taken to the same page. I had to use a backup to restore the cpanel to get the IOMAD working again. I tried adding a date field the same way with the same outcome and requiring another restore.  When I tried the the Moodle tools: Admin > Users > User Profile Fields, the new required user field was created successfully. I believe there is something wrong with this IOMAD tool which could potentially cause all sorts of trouble with unsuspecting users. 

Thanks-you,

Mark Iannone

**Comment by ndalpe** [comment]
Hi Markrico,
I have the same problem. I looked into the HTML and I think the problem (or part of it) is the custom field naming.

All the fields in the profile form are named with the same pattern:
<select class="custom-select" name="profile_field_region" id="id_profile_field_region">
<select class="custom-select" name="profile_field_Education" id="id_profile_field_Education">
So always "profile_field_" followed by the field's short name.

While the custom field created with IOMAD are named as follow:
<select class="custom-select" name="profile_field_<span class=&quot;multilang&quot; lang=&quot;en&quot;>Your Profile</span><span class=&quot;multilang&quot; lang=&quot;id&quot;>Profil Anda</span>blablabla" id="id_profile_field_spanclassmultilanglangenYourProfilespanspanclassmultilanglangidProfilAndaspanblablabla">

This part is the field category as described in mdl_user_info_category
"<span class=&quot;multilang&quot; lang=&quot;en&quot;>Your Profile</span><span class=&quot;multilang&quot; lang=&quot;id&quot;>Profil Anda</span>"

And "blablabla" is the field name

Test #2
I deleted the field in the database and recreated it but this time I put required to no. When I went back to my profile I have the following error:

Invalid admin setting (auth_cas/field_map_profile_field_Your ProfileProfil Andablablabla)

Debug info:
Error code: invalidadminsettingname 

Stack trace:
    line 1697 of /lib/adminlib.php: moodle_exception thrown
    line 1567 of /lib/adminlib.php: call to admin_setting->parse_setting_name()
    line 2146 of /lib/adminlib.php: call to admin_setting->__construct()
    line 1040 of /lib/authlib.php: call to admin_setting_configtext->__construct()
    line 275 of /auth/cas/settings.php: call to display_auth_lock_options()
    line 85 of /lib/classes/plugininfo/auth.php: call to include()
    line 133 of /admin/settings/plugins.php: call to core\plugininfo\auth->load_settings()
    line 7999 of /lib/adminlib.php: call to require()
    line 23 of /admin/search.php: call to admin_get_root()

This is as far as I can go. Please, tell me how I can help more?

Thank you

**Comment by ndalpe** [comment]
ok after a bit of digging I found a solution. It works for me to create and update the field.

https://github.com/iomad/iomad/blob/IOMAD_33_STABLE/blocks/iomad_company_admin/profiledefinelib.php
Line: 525 to 529

// Get the company shortname.
$category = $DB-&gt;get_record('user_info_category', array('id' =&gt; $data-&gt;categoryid));
// Collect the description and format back into the proper data structure from the editor.
// Note: This field will ALWAYS be an editor.
$data-&gt;shortname = $category-&gt;name . $data-&gt;shortname;

The comment says "Get the company shortname" but the code select the profile field category name. I changed the code for this:
// Get the company shortname.
$company = $DB-&gt;get_record('company', array('id' =&gt; $companyid));
// Collect the description and format back into the proper data structure from the editor.
// Note: This field will ALWAYS be an editor.
$data-&gt;shortname = $company-&gt;shortname . $data-&gt;shortname;


Problem:
Using the company shortname as custom field prefix can potentially cause an error since 
the function parse_setting_name($name) in [/lib/adminlib.php line 1694](https://github.com/iomad/iomad/blob/IOMAD_33_STABLE/lib/adminlib.php#L1694) is called when saving the field. This function perform a sanity check on the company shortname. The sanity check only allow these char [a-zA-Z0-9_]+. This is causing problem since we can add many more char in the company shortname field when creating a company.

ie: 
Bad company shortname:
"comp-shortname" will trow an "invalidadminsettingname" exeption because the - doesn't pass the saneity check

Good company shortname:
"comp_shortname" will pass the sanity check and everything works fine



Question:
What is the purpose of the company shortname prefix?
 - The custom field is displayed on the profile page of every user of every company
 - I can delete the prefix by going to Users -> User profile fields -> Edit field in Moodle

Hope this help guys

Keep the good work!

**Comment by turf212** [comment]
this was fixed a while back.
