### ISSUE TITLE
Multilang2 filter not working

### ISSUE THREAD

**Issue by glu000** [iomad/iomad#891]
The multilang2 plugin / filter is not working on iomad pages. E.g. if the multilang2 labels are used in the name-fields of a course it is shown on the page company_license_users_form.php in the following way:

`Lizenz ist gültig in folgenden Kursen: {mlang de}Changemanagement{mlang}{mlang en}Change Management{mlang}, {mlang de}Kommunikation{mlang}{mlang en}Communications{mlang}, {mlang de}Blended Learning Konfliktmanagement{mlang}{mlang en}Blended Learning Conflict Management{mlang}`

**Comment by glu000** [comment]
Same behavior in block_mycourses which is the standard block in the dashboard. Therefore the whole dashboard cannot be used in multi-language sites

@turf212: Would be great to get some feedback on this issue. This is a real blocker for multilanguage-sites

**Comment by MarkusKgit** [comment]
Seems like a function call to format_string() is needed in some places so that the filter can work. One example is here 9e8ad9f1b769d5ff59880101fceb01f2e7f20dcc

**Comment by ndalpe** [comment]
Hi Guys,
I am having the same problem as @glu000. Here I will post the fix for multi-language as I find them.
You can also help me in finding them and send me the URL so I can fix it too. I am open to suggestion if there is a better way to fix this problem.

IOMAD_34_STABLE

**/blocks/iomad_company_admin/company_license_list.php**
Line 235
Add this code after $coursename = $DB->get_record('course', array('id' => $licensecourse->courseid));
```
            // Process multi language course name
            $coursename->fullname = format_string($coursename->fullname, true, 1);
```

**/local/iomad/lib/company.php**
Line 1919
Add this code before the return statement
```
        // Take care of multilanguage
        foreach ($retcourses as $courseid => $course) {
            $retcourses[$courseid] = format_string($course, true, 1);
        }
```

**/local/iomad/lib/company.php**
Line 1707
Replace
```
            if ($courses = $DB->get_records_sql($sql)) {
                return $courses;
            }
```
by
```
            if ($courses = $DB->get_records_sql($sql)) {
                /*
                 * Format multi-language course full name
                */
                foreach ($courses as $key => $course) {
                    $courses[$key]->fullname = format_string($course->fullname, true, 1);
                }
                return $courses;
            }
```

**/local/course_selector/lib.php**
Line 611
Replace
```
        $bits = array(
            $course->fullname
        );
```

By

```
        $bits = array(
            format_string($course->fullname, true, 1)
        );
```


**/blocks/iomad_company_admin/iomad_courses_form.php**
Line 403
Replace
```
"<a href='$courselink'>$course->fullname</a>",
```
by
```
"<a href='$courselink'>".format_string($course->fullname, true, 1)."</a>",
```

**/blocks/iomad_company_admin/company_course_users_form.php**
Line 208
Replace
```
        $mform->addElement('header', 'header',
                            get_string('company_users_for', 'block_iomad_company_admin',
                            $course->fullname ));
```
by
```
        $mform->addElement('header', 'header',
                            get_string('company_users_for', 'block_iomad_company_admin',
                            format_string($course->fullname, true, 1) ));
```




that is it for now

**Comment by turf212** [comment]
Can you please add these as a pull request and I'll get them into the code?  I've made changes to the my courses block as per #944 but the rest would be appreciated please.

**Comment by turf212** [comment]
Ignore that.  I've gone through and added these.  Please raise any more which may need changed.

**Comment by ndalpe** [comment]
IOMAD 3.6

All these changes are here: https://github.com/ndalpe/iomad/commit/a2a85d187f1f935ea3577917e8e0bba4b22c584b


/blocks/iomad_company_admin/lib/course_selectors.php
Line 219
        // Make course name multilanguage compatible
        foreach ($coursearray["Company courses"] as $key => $value) {
            $coursearray["Company courses"][$key]->fullname = format_string($value->fullname, true, 1);
        }


/blocks/iomad_company_admin/lib/course_selectors.php
There are many more course name to translate in this file.
Line 478
        // Make course name multilanguage compatible
        foreach ($availablecourses as $key => $value) {
            $availablecourses[$key]->fullname = format_string($value->fullname, true, 1);
        }

Line 599
        // Make course name multilanguage compatible
        foreach ($availablecourses as $key => $value) {
            $availablecourses[$key]->fullname = format_string($value->fullname, true, 1);
        }

Line 693
            // Make course name multilanguage compatible
            foreach ($coursearray as $key => $value) {
                $coursearray[$key]->fullname = format_string($value->fullname, true, 1);
            }

Line 848
        // Make course name multilanguage compatible
        foreach ($availablecourses as $key => $value) {
            $availablecourses[$key]->fullname = format_string($value->fullname, true, 1);
        }


/local/iomad/lib/company.php
Line 1959
        // Make course name multilanguage compatible
        foreach ($retcourses as $key => $value) {
            $retcourses[$key] = format_string($value, true, 1);
        }


/blocks/iomad_company_admin/company_course_users_form.php
Line 210
        // Make course name multilanguage compatible
        $course->fullname = format_string($course->fullname, true, 1);


/blocks/iomad_company_admin/iomad_courses_table.php
Line 76
        // Make course name multilanguage compatible
        $row->coursename = format_string($row->coursename, true, 1);

https://192.168.33.10/blocks/iomad_company_admin/company_groups_users_form.php
Line 264
        // Make course name multilanguage compatible
        $course->fullname = format_string($course->fullname, true, 1);

/local/iomad_learningpath/manage.php
Line 49
//Make Learning path name and description multilanguage compatible
foreach ($paths as $key => $path) {
	$paths[$key]->name = format_string($path->name);
	$paths[$key]->description = format_string($path->description);
}

/local/iomad_learningpath/classes/companypaths.php
Line 81
            // Make path name multi language ready
            $path->name = format_string($path->name, true, 1);
            $path->description = format_string($path->description, true, 1);
Shouldn't we take the return out of the if and format_string just before the return?
Should also do get_paths() line 59


/local/iomad_learningpath/classes/companypaths.php
Line 288
        // Make course name multilanguage compatible
        foreach ($courses as $key => $value) {
            $courses[$key]->fullname = format_string($value->fullname, true, 1);
        }

Line 358
        // Make course name multilanguage compatible
        foreach ($courses as $key => $value) {
            $courses[$key]->fullname = format_string($value->fullname, true, 1);
        }

https://xxx.xxx.xxx.xxx/local/iomad_learningpath/editpath.php?id=1
Doesn't seems to keep the {mlang xx}{mlang} language string

That is it for tonight. There is a lot more to do, I will keep on the multi-language task if you like the provided code.

thx!!

**Comment by turf212** [comment]
Thats for doing this.  I added a bunch to the 3.6 code but it's mainly in places I could find them.  (Some are as above so if you could check and make sure they woudl that would be very useful :) )

**Comment by ndalpe** [comment]
The changes from Spt 6 seems to be integrated into 3.6.



We have a bug though in https://xxx/local/iomad_learningpath/editpath.php?id=2
Line 48 
$paths = $companypaths->get_paths(); 

The problem is that get_path() format the learning path name and desc in the edit form, removing the {mlang} tags and other language than the current lang. get_path() is also used to display the path name & desc which should be parsed through format_string.

Should we remove format_string from get_path() and format the LP name and desc in each individual file?

Thx

**Comment by ndalpe** [comment]
Teaching location:
https://github.com/ndalpe/iomad/commit/09112379da844e7d70ab183ba6fe9762b0448f40

From the code their seems to be much more to translate here but we are not using this module and I don't know how it works. Will try to find more later.

thx

**Comment by ndalpe** [comment]
your daily dose of multi-language 

Note:
$license doesn't seems to be used 
https://github.com/iomad/iomad/blob/ea5788d45677131bb5922391cd49a3ed219f1235/local/report_user_license_allocations/index.php#L333

Does a date needs a &lt;/br&gt;? It is displayed in the excel too (2019-03-07&lt;/br&gt;)
https://github.com/iomad/iomad/blob/ea5788d45677131bb5922391cd49a3ed219f1235/local/report_user_license_allocations/report_user_license_allocations_table.php#L118

Could be: $license = $licenses[$licenseid]; // reuse the $licenses var list from Line 176 and save a DB Query
https://github.com/iomad/iomad/blob/ea5788d45677131bb5922391cd49a3ed219f1235/local/report_license_usage/index.php#L248



Otherwise business as usual:

Dashboard - List Company Licenses
https://github.com/ndalpe/iomad/commit/c9088c24b5ad1837cd76efc0c75ee80a624bb4d8

Multi-language: Iomad Reports - User license allocations report 
https://github.com/ndalpe/iomad/commit/bc73489e51f0d684e19f7bb59874942ed6fa8b3d

Multi-language: License name in table and excel file 
https://github.com/ndalpe/iomad/commit/b44fca0e71fe2b65576e91179d04809352e07c5a

Multi-language: Dashboard - Manage user license allocations
https://github.com/ndalpe/iomad/commit/6fb1813c3b669717f89d8a511a75c26d183009d5

Multi-language: Iomad Reports - License allocations report
https://github.com/ndalpe/iomad/commit/b9b8dee74cc8131d563753e8c90baf158f70f627

Multi-language: Manage user enrolments
https://github.com/ndalpe/iomad/commit/dccfbb0f7e131dc74ea6c2977d6f8d43e9110b94
