### ISSUE TITLE
Multilanguage support: mixed languages in one sentence

### ISSUE THREAD

**Issue by glu000** [iomad/iomad#892]
If you set the Moodle-language to German, some iomad texts / messages have mixed languages in one sentence. This looks very funny, eg on page company_courses_form.php:

> Warnung: Wenn "(vorhandene Anmeldungen)" angezeigt werden you must tick the box beneath to allow add or remove. If you do this, alle Nutzer will be abgemeldet and ALL THEIR DATA (for that Kurs) IS LOST. This cannot be undone

Desired behavior would be to show only English texts, if the full text is not available in the selected language (in this case German)

**Comment by MarkusKgit** [comment]
@glu000 Since I'm also interested in correct german translations would you like to work on the translations with me? I started working on a local copy with the moodle built in language tools but I don't know if those can be shared? If not it would probably be better to edit/create the lang/de/*.php files manually and create a PR when done.
Maybe @turf212 can help here with the correct workflow.

**Comment by actXc** [comment]
I am planning to start a "deutsche sprache" fork for offering translation pull requests.
Would this be added value for your project?
Would you add translations?

**Comment by turf212** [comment]
If we could keep the language packs somewhere central this would be more desirable rather than having multiple forks of the code in different languages.  Specifically as I'm aware that we add in new string all of the time and it would be better to have some place which we could use something like Deepl to do the bulk of the translations.

**Comment by enrarelloem** [comment]
Any news on this?
About a month ago, I offered E-learn Design my German translation of the Iomad UI several times (two open tickets in their support system, open for more than a month now). No reaction.
The translations cover roughly 90+% of the UI.
If someone is interested, I could provide German local files which you can import into your installation.

**Comment by turf212** [comment]
I saw the ticket come in but I've been swamped by other work so was unable to respond.  My apologies.

The issue is that the Iomad plugin translations need to go into the same language pack files as for Moodle (as they are plugin files) but they cannot be loaded into AMOS (as the plugin files are not available to download from the plugins directory as you cannot simply install Iomad from there).  So there is currently no real way to contribute to the strings or community way to translate them all.

In case you didn't know, the translated files/language packs, all get put into /moodledata/lang/<language code> directories so they would need to be tied into the Moodle langiage packs (or the code changed to pull them from us instead but there also should be the capability of getting the Moodle strings langiage pack).  The process around this is non-trivial.  Never mind to test how an upgrade to the langiage pack would work through the Moodle language menus.

I've also had issues in the past where the translated strings were not the same generic Iomad strings so ended up that the string was tied for one company and wouldn't work for others. That was mainly because I trusted that they would have been generic but don't know the language (some people would argue I barely speak English ;) )

In saying all of this, I still think it is highly desirable to have a list of all of the strings and have translations for other languages.  It's also highly desirable to have this as a community project.  If you have thoughts on how this could work, please let me know.  E.g. there could be a master spreadsheet (on Goodle docs) which has the strings all listed with identifier and current value with separate tabs for translations.  If that worked OK and wasn't open to abuse then this could form the strings to be added to the lang file within the plugins themselves?

**Comment by actXc** [comment]
@enrarelloem  we have an iomad-translation project. May be we can join resources?

Not like the moodle AMOS, but also a nice translation-portal based on weblate: 
[https://translate.lms.link/](https://translate.lms.link/)

@turf212 
I was the uglyone with a inconsistent de tranlation some years ago. 
I pushed wrong files with "de" and theses should be removed, because the quality was not worth looking at it again. We tried to remove them but we where not able using github pull request again with my repo. 
Please remove the de-folder in
https://github.com/iomad/iomad/blob/IOMAD_38_STABLE/blocks/iomad_company_admin/lang/
`(older version)  local/iomad_dashboard/lang/`

as a much better alternative solutions, we invite everybody to add languages to 
[https://translate.lms.link/](https://translate.lms.link/)

DE is close to finish. 

practical: 
We put the files in `.../moodledata/lang/de_local  `
this enables us in a single installation to change single sentences using the moodle local language backend.

**Comment by enrarelloem** [comment]
> @enrarelloem we have an iomad-translation project. May be we can join resources?

@actXc 
I had a brief look at your project. However, I have three serious problems with it.
1) How does this feed back into iomad? Since you are almost finished and only minor parts of the translation have found the way back to the main project, I doubt that this is the best way to make a community project of the translation.
2) From the brief look, I saw that there are major differences between the iomad/E-Learn Design terminology and your approach to the translation.
E.g. "company" (Unternehmen) is translated as "Organisation" (organisation) which is more generic than company. I see your idea behind this. However, I have a corporate client where the backoffice was confused by "Organisation" as term for their customers. So I simply changed to the original Unternehmen (company) and they were happy.
A similar case is the translation of "big blue button" as "Videokonferenz". This might be ok in your setup and for your customers. I can see your intention, nevertheless, do I disagree with this obstruction to see the structure of the used applications.
3) The UI would make it necessary, that I copy all my translations manually into your interface. And this interface makes it rather hard to get a wider picture of your terminology since there is only one string on the screen at the time. I'd rather not use that.
 
@actXc and @turf212 
> We put the files in `.../moodledata/lang/de_local `
> this enables us in a single installation to change single sentences using the moodle local language backend.

This is what I did for my client. Since I'm not a developer and hardly "speak" git, I could provide these files. Alternatively, I would be willing to feed the strings from the language files into the GoogleDoc @turf212 suggested.
Having said that, I should stress that I'm a freelance e-learning consultant and designer and don't have unlimited resources timewise to contribute.

**Comment by turf212** [comment]
@enrarelloem I agree with you on the words.  Things like BigBlueButton are product names and should not be translated to something else.  We should also be keeping the words as close to the originals as possible.  If someone wants to further change them then they can do so in the Moodle language customisation tools.

Would you be able to send me the zipped up lang files?  Do you know which strings are the ~ 10% you have not translated?

For an overall solution for this I have been rationalising the language strings in 3.8 (and am continuing in 3.9) so that we use the Moodle lanhuage packs as much as possible to reduce the amount of translations.  We can then use something like Deepl (https://www.deepl.com/en/translator) to provide initial translations but I don't trust them to be exact and we'd need to be mindful of:
1 - How we put the string up there to be translated so we can keep the string identifier and plugin parts consistent
2 - The string placeholders which are used as variables don't get broken with the translation either.

So it would need a native speaking person to read through the strings to make sure that they are accurate once it had been run (which is always the issue with translation software but this one appears to be better than most if limited in languages).

**Comment by mrmuehle** [comment]
We use the WEBLATE translation plattform. (free open source) 
All translated files can be downloaded as ZIP, HEre ist the link:  https://translate.lms.link/download/iomaddata-lang/?format=zip

the brand names can be  searched and replaced within the weblate tool very ergonimicaly,
I agree to do this, but also our translation comes from a customer project.

Weblate can also import php-files. If you have more translations, please add.
We have used goole API to translate quickly, then we did some manual adjustments.

We use the original placeholders and the php lang files work well - (except for e.g. the email templates, we had to change the lin feed into standard syntax. )
We could have a second translation project or join resources. 

Our team is native speaking German, the WEBLATE platform allows to define roles to have all kind of diffrent

**Comment by mrmuehle** [comment]
>     1. How does this feed back into iomad? Since you are almost finished and only minor parts of the translation have found the way back to the main project, I doubt that this is the best way to make a community project of the translation.

It is the practial way we had to go to involve many translators, because of th e big amount of text.
Now we want to share this in the best way we can with the IOMAD project.

**Comment by mrmuehle** [comment]
>     3\. The UI would make it necessary, that I copy all my translations manually into your interface. And this interface makes it rather hard to get a wider picture of your terminology since there is only one string on the screen at the time. I'd rather not use that.

USe the "ZEN" translation mode, or use the many tool provided, it has the option to show auto translation ,translation mamory, near translation related to the finding in the files

**Comment by enrarelloem** [comment]
@turf212 Being a native speaker with some background in languages, I'd could proofread the German translations.

@mrmuehle As said before, I see general problems with your approach to the translation of the UI (see @turf212's comments above, too). So I'd rather stick with my translation - which just took some 20+ hrs. for most of the user interface.
