### ISSUE TITLE
Client Course Editor role can't be removed from course

### ISSUE THREAD

**Issue by pm-tatiana** [iomad/iomad#992]
Use Case: 
Company Manager of ACME company creates a course inside the company.
For some reason, that course must be "transferred" to another company. 
Site Admin, changes Course sharing setting to closed shared, unassign the course from the company (checking the OK to unenroll checkbox) and then assign the course to the new company.

Issue is: Company manager from the previous company can still edit the course. I noticed that it is because the role Client Course Editor is preserved and not removed when the user is unenrolled from course.

Any advise?
rgds
Tatiana

**Comment by turf212** [comment]
There is a table which lists courses that have been created by a company which will be causing you issues here.  We've never had a use case where a course created by a company is removed and then added to another company.  W could remove the relation so that company managers from company A were removed but then if you wanted company managers from company B to be a client course editor it would make it difficult as the mechanism isn't there.  You could, instead, create the course in company B ad back up and restore (as there is a manual process for moving it anyway) and this would solve the second issue (if that is a use case...)

**Comment by turf212** [comment]
I realise this was a long time ago, so if you did come up with a solution please let me know :)
